/* The picture on a skill's disc.

   The tree used to show Duolingo's own skill drawings, cut from three sprite
   sheets scraped off duome.eu — Duolingo's property, and a second visual
   language beside the line icons everything else in the app is drawn with.
   Now a skill is drawn with a Lucide glyph (ISC licence), chosen from the
   skill's name: the first rule that matches wins, so "Reading: Bialik" is a
   book and "Past Pi'el" is a verb before either is anything else. Anything
   no rule knows gets a spark. */
import {
  Type, MessageSquare, Egg, Box, Paintbrush, Utensils, Cat, Layers, Hand, Target,
  Shirt, Palette, ArrowRightLeft, Hash, MessageCircleQuestion, TextCursor, Briefcase,
  Link, CalendarDays, Clock, Gauge, Users, Home, Puzzle, Infinity as InfinityIcon,
  CloudSun, MapPin, User, GraduationCap, Plane, Scale, Shapes, Megaphone, Globe,
  Siren, Leaf, MessagesSquare, Heart, Triangle, Stethoscope, Sparkles, Smartphone,
  Repeat, FlaskConical, Music, Medal, Landmark, Minimize2, Scroll, Rocket, PartyPopper,
  Map as MapIcon, Sprout, ChefHat, ShoppingBag, HeartPulse, Bus, Building2, Laptop,
  TreePine, Bike, LayoutGrid, GitBranch, Activity, Building, Coins, Newspaper, Quote,
  RotateCcw, Tag, Split, BookOpen, Feather, Library, Mail, FileText, Shield, KeyRound,
  AtSign, Clapperboard, Image as ImageIcon, Brain, Cpu, Laugh, SpellCheck,
  SlidersHorizontal, PenLine, MoreHorizontal, ArrowUpDown, Braces, Flag, Ear,
  Headphones, Hourglass, History, FastForward, Zap, Lightbulb, Star, Wrench,
} from "lucide-react";

const RULES = [
  [/^letters/i, Type],
  [/^common phrases/i, MessageSquare],
  [/^basics$/i, Egg],
  [/there is|to have/i, Box],
  [/adjective/i, Paintbrush],
  [/^food|menus|recipes|cooking/i, Utensils],
  [/animals/i, Cat],
  [/plurals/i, Layers],
  [/possessive/i, Hand],
  [/direct object/i, Target],
  [/clothing/i, Shirt],
  [/^colors|^arts$/i, Palette],
  [/preposition/i, ArrowRightLeft],
  [/numbers/i, Hash],
  [/questions/i, MessageCircleQuestion],
  [/determiners/i, TextCursor],
  [/occupations|business|work life/i, Briefcase],
  [/conjunction|connectives/i, Link],
  [/dates and time|dates/i, CalendarDays],
  [/time words/i, Clock],
  [/adverbs/i, Gauge],
  [/family|people/i, Users],
  [/home sweet home|housing|renting/i, Home],
  [/construct state/i, Puzzle],
  [/infinitives/i, InfinityIcon],
  [/weather/i, CloudSun],
  [/places|getting around/i, MapPin],
  [/pronouns/i, User],
  [/education|academia|academic/i, GraduationCap],
  [/travel|immigration|welcome to israel/i, Plane],
  [/comparison|law|legal|contracts/i, Scale],
  [/abstract/i, Shapes],
  [/imperative/i, Megaphone],
  [/languages|loanwords|arabic|borrowed|false friends/i, Globe],
  [/emergency/i, Siren],
  [/nature|environment|ecology/i, Leaf],
  [/discussions|conversation|opinion|debate|rhetoric/i, MessagesSquare],
  [/feelings|emotions/i, Heart],
  [/geometry/i, Triangle],
  [/medical|doctor|health|body/i, Stethoscope],
  [/technology|tech|digital|phone|internet|chat hebrew|text messages/i, Smartphone],
  [/verbal noun|participle/i, Repeat],
  [/science|research/i, FlaskConical],
  [/music|songs|proverbs/i, Music],
  [/sports/i, Medal],
  [/politics|citizen|bureaucra|banking|forms$/i, Landmark],
  [/diminutives/i, Minimize2],
  [/legends|storytell|narrative|children's literature/i, Scroll],
  [/outer space/i, Rocket],
  [/festivals|holidays/i, PartyPopper],
  [/geography/i, MapIcon],
  [/root|weak roots|denominal/i, Sprout],
  [/shopping|shuk/i, ShoppingBag],
  [/wellness/i, HeartPulse],
  [/transport/i, Bus],
  [/city life/i, Building2],
  [/hobbies/i, Bike],
  [/word patterns|mishkalim|binyan/i, LayoutGrid],
  [/relative clauses/i, GitBranch],
  [/economy/i, Coins],
  [/news/i, Newspaper],
  [/idioms|reported speech|quote/i, Quote],
  [/review|error correction/i, RotateCcw],
  [/suffix|names & acronyms/i, Tag],
  [/conditional/i, Split],
  [/^reading|chapter reading|comprehension|wikipedia|encyclopedia/i, BookOpen],
  [/poetry|literary/i, Feather],
  [/biblical|period:/i, Hourglass],
  [/formal|letters$/i, Mail],
  [/army|military/i, Shield],
  [/film|television|media|comics/i, Clapperboard],
  [/philosophy|psychology/i, Brain],
  [/ai\b/i, Cpu],
  [/humor|slang|taboo/i, Laugh],
  [/register/i, SlidersHorizontal],
  [/writing|paragraph/i, PenLine],
  [/discourse|filler/i, MoreHorizontal],
  [/word order/i, ArrowUpDown],
  [/syntax|constructs/i, Braces],
  [/checkpoint/i, Flag],
  [/native ear/i, Ear],
  [/listening/i, Headphones],
  [/^past/i, History],
  [/^future/i, FastForward],
  [/present|verbs?:|pa'al|pi'el|hif'il|hiph'il|hitpa'el|nif'al|passive|pu'al|huf'al|modals/i, Zap],
  [/objects/i, Box],
  [/neologisms|contemporary|technology now/i, Lightbulb],
  [/religion/i, Star],
  [/history/i, Hourglass],
  [/vocabulary|words/i, Type],
];

export function skillIcon(unit) {
  const name = unit?.skill || "";
  for (const [re, Icon] of RULES) if (re.test(name)) return Icon;
  return Sparkles;
}

/* the guidebook's tools icon, for anything that reads as "how it works" */
export { Wrench };
