/* What a unit is called.

   The course data names a unit by its Duolingo skill ("Verbs: Present Reflexive
   - Hitpa'el") and abbreviates it for narrow screens ("Pres.Reflx"), neither of
   which fits under a node on the path. These are the same skills under names
   short enough to print there, one line each. */

const NAMES = {
  1: "Letters 1",
  2: "Letters 2",
  3: "Letters 3",
  4: "Greetings",
  5: "Basics",
  6: "There Is",
  7: "Adjectives",
  8: "Food 1",
  9: "Animals",
  10: "Plurals",
  11: "Possessives 1",
  12: "Adjectives 1",
  13: "Direct Object",
  14: "Food 2",
  15: "Clothing",
  16: "Present Pa'al",
  17: "Colors",
  18: "Prepositions 1",
  19: "Numbers 1",
  20: "Questions",
  21: "Determiners",
  22: "Occupations",
  23: "Conjunctions",
  24: "Prepositions 2",
  25: "Possessives 2",
  26: "Present Pi'el",
  27: "Time & Dates",
  28: "Adjectives 2",
  29: "Adverbs",
  30: "Family",
  31: "Home",
  32: "Construct 1",
  33: "Infinitives 1",
  34: "Weather",
  35: "Places",
  36: "Present Hif'il",
  37: "People",
  38: "Numbers 2",
  39: "Modals",
  40: "Education",
  41: "Travel",
  42: "Past Tense 1",
  43: "Comparison",
  44: "Objects",
  45: "Hitpa'el Verbs",
  46: "Adjectives 3",
  47: "Abstract 1",
  48: "Commands 1",
  49: "Languages",
  50: "Emergency",
  51: "Future Tense",
  52: "Passive Voice",
  53: "Reflexives",
  54: "Nif'al Verbs",
  55: "Nature",
  56: "Discussion",
  57: "Commands 2",
  58: "Past Tense 2",
  59: "Past Nif'al",
  60: "Feelings",
  61: "Geometry",
  62: "Abstract 2",
  63: "Infinitives 2",
  64: "Construct 2",
  65: "Conditional",
  66: "Medical",
  67: "Future Tense 2",
  68: "Religion",
  69: "Arts",
  70: "Don't!",
  71: "Technology",
  72: "Verbal Nouns",
  73: "Science",
  74: "Music",
  75: "Sports",
  76: "Politics",
  77: "Diminutives",
  78: "Legends",
  79: "Future Nif'al",
  80: "Formal",
  81: "Business",
  82: "Outer Space",
  83: "Festivals",
  84: "Israel",
};

/* The course JSON is the source of truth for which units exist, so a unit the
   table has never heard of still gets a name. A unit too big for one card is
   drawn as two, which are the same name with p1 and p2 after it. */
export const unitName = (unit) => {
  const name = NAMES[unit?.unit] || unit?.short || unit?.skill || `Unit ${unit?.unit}`;
  return unit?.part ? `${name} p${unit.part}` : name;
};
