/* Level 5 — מִבְנֶה וְסִגְנוֹן · Structure and register.

   Everything up to here builds single clauses. This level joins them, and
   introduces the gap between how Hebrew is spoken and how it is written —
   which is the wall a learner hits the moment they open a book. */

export default {
  level: 5,
  name: "Structure and style",
  nameHe: "מִבְנֶה וְסִגְנוֹן",
  blurb: "Joining clauses, conditionals, verbal nouns, and the distance between spoken and written Hebrew.",
  lessons: [
    {
      id: "s1",
      title: "Joining clauses",
      titleHe: "מִשְׁפָּט מְחֻבָּר",
      goal: "Use שֶׁ, כִּי and כְּדֵי to build sentences longer than one clause.",
      sections: [
        { type: "text", body: "שֶׁ is the workhorse. Glued to the front of a clause it does the job of English that, which and who all at once — and unlike English, it is never optional." },
        {
          type: "examples", items: [
            { he: "אֲנִי חוֹשֵׁב שֶׁהוּא צוֹדֵק.", en: "I think (that) he's right." },
            { he: "הָאִישׁ שֶׁבָּא אֶתְמוֹל", en: "the man who came yesterday" },
            { he: "הַסֵּפֶר שֶׁקָּרָאתִי", en: "the book (that) I read" },
            { he: "כְּשֶׁהִגַּעְתִּי, הוּא כְּבָר הָלַךְ.", en: "When I arrived, he'd already left." },
          ],
        },
        {
          type: "table", caption: "Connectors",
          head: ["Hebrew", "English"],
          rows: [
            ["שֶׁ", "that, which, who"],
            ["כִּי", "because"],
            ["כְּדֵי", "in order to"],
            ["אֲבָל", "but"],
            ["לִפְנֵי שֶׁ", "before"],
            ["אַחֲרֵי שֶׁ", "after"],
            ["בִּגְלַל שֶׁ", "because of the fact that"],
          ],
        },
        { type: "tip", body: "אֲשֶׁר is שֶׁ in literary dress — same meaning, separate word, and everywhere in older prose. When you meet it, read it as שֶׁ." },
      ],
      vocab: [
        { he: "שֶׁ", en: "that, which, who", translit: "she-" },
        { he: "כִּי", en: "because", translit: "ki" },
        { he: "אֲשֶׁר", en: "that, which (literary)", translit: "asher" },
        { he: "כְּדֵי", en: "in order to", translit: "kdei" },
        { he: "אֲבָל", en: "but", translit: "aval" },
        { he: "לָכֵן", en: "therefore", translit: "lachen" },
        { he: "לְמָשָׁל", en: "for example", translit: "lemashal" },
        { he: "בְּעֶצֶם", en: "actually", translit: "be'etsem" },
      ],
      drills: ["vocab", "build"],
    },
    {
      id: "s7",
      title: "Saying when",
      titleHe: "פִּסְקַת זְמַן",
      goal: "Attach a clause of time — before, after, while, until, ever since.",
      sections: [
        { type: "text", body: "Almost every word for when in Hebrew is a preposition with שֶׁ stuck on the end. The preposition takes a noun; add שֶׁ and it takes a whole clause instead. That one rule generates the entire table below." },
        {
          type: "table", caption: "Before a noun, and before a clause",
          head: ["meaning", "with a noun", "with a clause"],
          rows: [
            ["before", "לִפְנֵי הָאֲרוּחָה", "לִפְנֵי שֶׁאָכַלְנוּ"],
            ["after", "אַחֲרֵי הַשִּׁעוּר", "אַחֲרֵי שֶׁגָּמַרְנוּ"],
            ["until", "עַד הָעֶרֶב", "עַד שֶׁהוּא בָּא"],
            ["since", "מֵאָז הַבֹּקֶר", "מֵאָז שֶׁהוּא הָלַךְ"],
            ["during, while", "בִּזְמַן הָעֲבוֹדָה", "בִּזְמַן שֶׁעָבַדְתִּי"],
          ],
        },
        { type: "text", body: "Two more do not follow the pattern and have to be learned as they are: כְּשֶׁ, when, which only ever takes a clause; and כָּל עוֹד, as long as, which takes one without any שֶׁ at all." },
        {
          type: "table", caption: "The rest of the set",
          head: ["meaning", "Hebrew"],
          rows: [
            ["when", "כְּשֶׁ־"],
            ["when — in writing", "כַּאֲשֶׁר"],
            ["the moment that", "בָּרֶגַע שֶׁ־"],
            ["every time that", "כָּל פַּעַם שֶׁ־"],
            ["as long as", "כָּל עוֹד"],
            ["while, in the time that", "בְּעוֹד"],
          ],
        },
        {
          type: "examples", items: [
            { he: "כְּשֶׁהָיִיתִי יֶלֶד גַּרְנוּ בַּכְּפָר.", en: "When I was a child we lived in the village." },
            { he: "חִכִּיתִי עַד שֶׁהִיא חָזְרָה.", en: "I waited until she came back." },
            { he: "לִפְנֵי שֶׁתֵּלֵךְ, תֵּן לִי דַּקָּה.", en: "Before you go, give me a minute." },
            { he: "כָּל עוֹד יֵשׁ זְמַן, אֶפְשָׁר לְחַכּוֹת.", en: "As long as there's time, one can wait." },
          ],
        },
        { type: "tip", body: "לִפְנֵי שֶׁ and אַחֲרֵי שֶׁ take a tensed verb, not an infinitive. English says before going; Hebrew says before that I went — לִפְנֵי שֶׁהָלַכְתִּי — and the tense follows the main clause." },
      ],
      vocab: [
        { he: "כְּשֶׁ", en: "when", translit: "kshe" },
        { he: "לִפְנֵי שֶׁ", en: "before (a clause)", translit: "lifnei she" },
        { he: "אַחֲרֵי שֶׁ", en: "after (a clause)", translit: "acharei she" },
        { he: "עַד שֶׁ", en: "until", translit: "ad she" },
        { he: "מֵאָז שֶׁ", en: "ever since", translit: "me'az she" },
        { he: "בִּזְמַן שֶׁ", en: "while", translit: "bizman she" },
        { he: "כָּל עוֹד", en: "as long as", translit: "kol od" },
        { he: "בָּרֶגַע שֶׁ", en: "the moment that", translit: "barega she" },
      ],
      drills: ["vocab", "when", "build"],
    },
    {
      id: "s2",
      title: "If",
      titleHe: "תְּנַאי",
      goal: "Tell a real condition from an impossible one.",
      sections: [
        { type: "text", body: "אִם is for things that might happen, and takes the future. לוּ and אִילוּ are for things that didn't, and take the past — with הָיָה carrying the counterfactual." },
        {
          type: "examples", items: [
            { he: "אִם יִהְיֶה זְמַן, נֵלֵךְ.", en: "If there's time, we'll go." },
            { he: "אִילוּ יָדַעְתִּי, הָיִיתִי בָּא.", en: "Had I known, I would have come." },
            { he: "לוּ הָיָה לִי כֶּסֶף…", en: "If only I had money…" },
          ],
        },
        { type: "tip", body: "The counterfactual is built with הָיָה plus the present participle: הָיִיתִי בָּא, I would have come. It's the one place the present tense is used to talk about the past." },
      ],
      vocab: [
        { he: "אִם", en: "if", translit: "im" },
        { he: "אִילוּ", en: "if (contrary to fact)", translit: "ilu" },
        { he: "אוּלַי", en: "maybe", translit: "ulai" },
        { he: "בְּלִי", en: "without", translit: "bli" },
        { he: "אַף עַל פִּי כֵן", en: "nevertheless", translit: "af al pi chen" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "“Had I known, I would have come.”", options: ["אִילוּ יָדַעְתִּי, הָיִיתִי בָּא", "אִם יָדַעְתִּי, אָבוֹא", "אִם אֵדַע, בָּאתִי", "אִילוּ אֵדַע, אֲנִי בָּא"], correct: 0, why: "A condition that didn't happen takes אִילוּ with the past, and הָיָה plus the participle in the result." },
      ],
    },
    {
      id: "s3",
      title: "The act itself",
      titleHe: "שֵׁם פְּעֻלָּה",
      goal: "Recognise verbal nouns — the reading, the writing, the development.",
      sections: [
        { type: "text", body: "Each binyan turns its verbs into nouns by a fixed pattern. Once you see the pattern you can read a noun you've never met and know both what it means and which verb it came from." },
        {
          type: "table", caption: "Verb to noun",
          head: ["binyan", "verb", "noun"],
          rows: [
            ["פָּעַל", "כּוֹתֵב writes", "כְּתִיבָה writing"],
            ["פָּעַל", "קוֹרֵא reads", "קְרִיאָה reading"],
            ["פִּעֵל", "מְדַבֵּר speaks", "דִּבּוּר speech"],
            ["פִּעֵל", "מְטַיֵּל travels", "טִיּוּל a trip"],
            ["הִפְעִיל", "מַסְבִּיר explains", "הַסְבָּרָה explanation"],
            ["הִתְפַּעֵל", "מִתְפַּתֵּחַ develops", "הִתְפַּתְּחוּת development"],
          ],
        },
        { type: "tip", body: "This is the single most useful pattern for reading. A page of literary Hebrew is full of nouns you've never seen whose verbs you already know." },
      ],
      vocab: [
        { he: "כְּתִיבָה", en: "writing", translit: "ktiva" },
        { he: "קְרִיאָה", en: "reading, a call", translit: "kri'a" },
        { he: "דִּבּוּר", en: "speech, speaking", translit: "dibur" },
        { he: "סִפּוּר", en: "story", translit: "sipur" },
        { he: "הַתְחָלָה", en: "beginning", translit: "hatchala" },
        { he: "הַרְגָּשָׁה", en: "feeling", translit: "hargasha" },
        { he: "הִתְפַּתְּחוּת", en: "development", translit: "hitpatchut" },
      ],
      drills: ["vocab", "verbal-noun"],
    },
    {
      id: "s8",
      title: "How words are built",
      titleHe: "מִשְׁקָלִים",
      goal: "Read a word you have never met by recognising the shape it was poured into.",
      sections: [
        { type: "text", body: "A Hebrew word is a root poured into a pattern — a מִשְׁקָל. The root carries the meaning, the pattern says what kind of word it is: a place, a tool, a trade, an abstraction. Learn eight patterns and a large part of the dictionary stops needing to be looked up." },
        {
          type: "table", caption: "Patterns worth knowing on sight",
          head: ["pattern", "what it makes", "example"],
          rows: [
            ["מִקְטָל", "the place where it happens", "מִטְבָּח — kitchen, from ט־ב־ח, to cook"],
            ["מַקְטֵל, מַקְטֵלָה", "the tool that does it", "מַפְתֵּחַ — key, from פ־ת־ח, to open"],
            ["קַטָּל", "the trade that does it all day", "נַגָּר — carpenter, from נ־ג־ר"],
            ["קַטְלָן", "the person who is like that", "שַׂחְקָן — actor, from שׂ־ח־ק, to play"],
            ["קְטִילָה", "the act itself", "כְּתִיבָה — writing, from כ־ת־ב"],
            ["־וּת", "the abstraction of it", "יַלְדוּת — childhood, from יֶלֶד"],
            ["־ִיָּה", "the place that sells or holds it", "סִפְרִיָּה — library, from סֵפֶר"],
            ["־ִי", "an adjective made from a noun", "חָפְשִׁי — free, from חֹפֶשׁ"],
          ],
        },
        { type: "text", body: "The value of this is not tidiness. It is that an unknown word stops being opaque: מַצְלֵמָה is the מַקְטֵלָה tool pattern over צ־ל־ם, to photograph, so it is the thing you photograph with, and you have translated camera without a dictionary." },
        {
          type: "examples", items: [
            { he: "מַאֲפִיָּה", en: "a bakery — the ־ִיָּה place, over א־פ־ה, to bake" },
            { he: "גַּנָּב", en: "a thief — the קַטָּל trade, over ג־נ־ב, to steal" },
            { he: "חֵרוּת", en: "freedom — the ־וּת abstraction" },
            { he: "מַזְלֵג", en: "a fork — the מַקְטֵל tool" },
          ],
        },
        { type: "tip", body: "This is also why a Hebrew dictionary is organised by root rather than by spelling, and why looking a word up means stripping ו, ה, ב, ל, כ, מ, שׁ off the front and the pattern off around it first." },
        { type: "tip", body: "The patterns are productive, which is how the language absorbed a century of new things without borrowing much: מַדְפֶּסֶת, printer, is the tool pattern over ד־פ־ס, and was made the same way מַפְתֵּחַ was, three thousand years earlier." },
      ],
      vocab: [
        { he: "נַגָּר", en: "carpenter", translit: "nagar" },
        { he: "גַּנָּב", en: "thief", translit: "ganav" },
        { he: "שַׂחְקָן", en: "actor, player", translit: "sachkan" },
        { he: "סִפְרִיָּה", en: "library", translit: "sifriya" },
        { he: "מַאֲפִיָּה", en: "bakery", translit: "ma'afiya" },
        { he: "מַצְלֵמָה", en: "camera", translit: "matslema" },
        { he: "יַלְדוּת", en: "childhood", translit: "yaldut" },
        { he: "חֵרוּת", en: "freedom", translit: "cherut" },
      ],
      drills: ["vocab", "mishkal", "type"],
    },
    {
      id: "s4",
      title: "How it's done",
      titleHe: "תֹּאַר הַפֹּעַל",
      goal: "Modify a verb — with an adverb, or with a preposition and a noun.",
      sections: [
        { type: "text", body: "Hebrew has fewer true adverbs than English and makes up the difference with בְּ plus an abstract noun: בְּשֶׁקֶט quietly, literally in quiet." },
        {
          type: "examples", items: [
            { he: "הוּא מְדַבֵּר מַהֵר.", en: "He speaks quickly." },
            { he: "הִיא כָּתְבָה בִּזְהִירוּת.", en: "She wrote carefully." },
            { he: "אֲנִי מַכִּיר אוֹתוֹ הֵיטֵב.", en: "I know him well." },
          ],
        },
        { type: "tip", body: "טוֹב is an adjective doing adverb duty in speech — הוּא כּוֹתֵב טוֹב. In writing you'd want הֵיטֵב." },
      ],
      vocab: [
        { he: "מַהֵר", en: "quickly", translit: "maher" },
        { he: "לְאַט", en: "slowly", translit: "le'at" },
        { he: "הֵיטֵב", en: "well, thoroughly", translit: "heitev" },
        { he: "מְאוֹד", en: "very", translit: "me'od" },
        { he: "תָּמִיד", en: "always", translit: "tamid" },
        { he: "לִפְעָמִים", en: "sometimes", translit: "lif'amim" },
        { he: "כְּבָר", en: "already", translit: "kvar" },
        { he: "בְּשֶׁקֶט", en: "quietly", translit: "besheket" },
      ],
      drills: ["vocab", "listen"],
    },
    {
      id: "s5",
      title: "Word order",
      titleHe: "סֵדֶר הַמִּלִּים",
      goal: "Know the default order, and what moving a word does.",
      sections: [
        { type: "text", body: "Modern Hebrew is subject–verb–object, like English. Literary and biblical Hebrew often puts the verb first, which is why an old sentence can read as inverted before you've parsed it." },
        {
          type: "examples", items: [
            { he: "הַיֶּלֶד קָרָא אֶת הַסֵּפֶר.", en: "The boy read the book. — ordinary" },
            { he: "קָרָא הַיֶּלֶד אֶת הַסֵּפֶר.", en: "Read the boy the book. — literary, same meaning" },
            { he: "אֶת הַסֵּפֶר קָרָא הַיֶּלֶד.", en: "It was the book the boy read. — fronted for emphasis" },
          ],
        },
        { type: "tip", body: "Because the verb ending already tells you the person, Hebrew can drop the subject pronoun entirely in the past and future. הָלַכְתִּי is a complete sentence." },
      ],
      vocab: [
        { he: "דַּוְקָא", en: "specifically, of all things", translit: "davka" },
        { he: "גַּם", en: "also", translit: "gam" },
        { he: "אֲפִלּוּ", en: "even", translit: "afilu" },
        { he: "בִּכְלָל", en: "at all, in general", translit: "bichlal" },
        { he: "כָּךְ", en: "thus, so", translit: "kach" },
      ],
      drills: ["vocab", "build"],
    },
    {
      id: "s6",
      title: "Written and spoken",
      titleHe: "מִשְׁלָב",
      goal: "Read the formal forms that speech has dropped.",
      sections: [
        { type: "text", body: "Written Hebrew keeps forms that conversation has abandoned. Neither is more correct — but a book uses the left column, and you will not have heard it." },
        {
          type: "table", caption: "Same meaning, two registers",
          head: ["written", "spoken", "meaning"],
          rows: [
            ["אֲשֶׁר", "שֶׁ", "that, which"],
            ["אֵינֶנִּי יוֹדֵעַ", "אֲנִי לֹא יוֹדֵעַ", "I don't know"],
            ["בֵּיתִי", "הַבַּיִת שֶׁלִּי", "my house"],
            ["כַּאֲשֶׁר", "כְּשֶׁ", "when"],
            ["רַבִּים", "הַרְבֵּה", "many"],
            ["הִנֵּה", "הִנֵּה / זֶה", "here is"],
          ],
        },
        { type: "text", body: "The possessive suffix is the one to know: instead of הַבַּיִת שֶׁלִּי, literary Hebrew attaches the pronoun to the noun." },
        {
          type: "table", caption: "Possessive suffixes",
          head: ["form", "meaning"],
          rows: [
            ["בֵּיתִי", "my house"], ["בֵּיתְךָ", "your (m.) house"], ["בֵּיתוֹ", "his house"],
            ["בֵּיתָהּ", "her house"], ["שְׁמוֹ", "his name"], ["יָדָהּ", "her hand"],
            ["דְּבָרַי", "my words"],
          ],
        },
      ],
      vocab: [
        { he: "אֵינֶנִּי", en: "I am not (literary)", translit: "eineni" },
        { he: "כַּאֲשֶׁר", en: "when (literary)", translit: "ka'asher" },
        { he: "הִנֵּה", en: "here is, behold", translit: "hine" },
        { he: "בֵּיתוֹ", en: "his house", translit: "beito" },
        { he: "שְׁמוֹ", en: "his name", translit: "shmo" },
        { he: "דָּבָר", en: "thing, word", translit: "davar" },
      ],
      drills: ["vocab", "register"],
    },
    {
      id: "s9",
      title: "Marks on the page",
      titleHe: "גֵּרֵשׁ וְגֵרְשַׁיִם",
      goal: "Read the two marks, the letter-numbers and the abbreviations a real page is full of.",
      sections: [
        { type: "text", body: "Hebrew has two punctuation marks of its own, and neither is an apostrophe or a quotation mark, though both are typed with those keys. They mark shortened words, and a printed page is full of them." },
        {
          type: "table", caption: "The two marks",
          head: ["mark", "what it means", "example"],
          rows: [
            ["׳ — גֵּרֵשׁ", "one word cut short", "עמ׳ — short for עַמּוּד, page"],
            ["״ — גֵּרְשַׁיִם", "several words as initials", "תנ״ך — Torah, Prophets, Writings"],
            ["׳ on a letter — a foreign sound", "a sound Hebrew lacks", "ג׳ — j, as in ג׳וּנְגֶּל"],
            ["־ — מַקָּף", "a hyphen joining words", "עַל־יְדֵי — by means of"],
          ],
        },
        { type: "text", body: "The gershayim sits before the last letter of the abbreviation, which is how you tell it from a quotation mark at a glance. And letters do duty as numbers: א is 1, י is 10, ק is 100 — so a page number, a chapter, or a Hebrew year is spelled rather than counted." },
        {
          type: "table", caption: "Abbreviations you will meet on any page",
          head: ["short", "meaning", "written out"],
          rows: [
            ["עמ׳ — page", "page", "עַמּוּד"],
            ["וכו׳ — et cetera", "et cetera", "וְכוּלֵּי"],
            ["ד״ר — Dr", "doctor", "דּוֹקְטוֹר"],
            ["בע״מ — Ltd", "a limited company", "בְּעֵרָבוֹן מֻגְבָּל"],
            ["ת״א — Tel Aviv", "Tel Aviv", "תֵּל אָבִיב"],
            ["אחה״צ — p.m.", "afternoon", "אַחַר הַצָּהֳרַיִם"],
          ],
        },
        { type: "tip", body: "An abbreviation you cannot crack is usually a source rather than a word — a title, a tractate, an author — and older printing shortens exactly those the hardest. When one blocks a sentence, read past it: it is almost always a citation you can look up later." },
        { type: "tip", body: "Nothing in a Hebrew text tells you where a quotation begins — quotation marks are recent, and older books use none. In Bialik or Brenner, speech is often marked by nothing but a dash at the start of the line." },
      ],
      vocab: [
        { he: "עַמּוּד", en: "page, column", translit: "amud" },
        { he: "אוֹת", en: "a letter of the alphabet", translit: "ot" },
        { he: "שׁוּרָה", en: "a line of text", translit: "shura" },
        { he: "כּוֹתֶרֶת", en: "a heading, a title", translit: "koteret" },
        { he: "נְקֻדָּה", en: "a full stop, a point", translit: "nekuda" },
        { he: "פְּסִיק", en: "a comma", translit: "psik" },
        { he: "סִימָן", en: "a sign, a mark", translit: "siman" },
        { he: "הֶעָרָה", en: "a note, a remark", translit: "he'ara" },
      ],
      drills: ["vocab", "marks"],
    },
  ],
};
