/* Level 3 — אוּלְפָּן ב׳ · Possession, the past, and joining words together. */

export default {
  level: 3,
  name: "Ulpan Bet",
  nameHe: "אוּלְפָּן ב׳",
  blurb: "Owning things, saying what happened, and the endings Hebrew hangs on its prepositions.",
  lessons: [
    {
      id: "b1",
      title: "Whose it is",
      titleHe: "שֶׁל",
      goal: "Say that something belongs to someone.",
      sections: [
        { type: "text", body: "שֶׁל is of. It goes between the thing and its owner, and the thing takes the article: הַסֵּפֶר שֶׁל דָּוִד, David's book — literally the book of David." },
        { type: "text", body: "With a pronoun, שֶׁל takes an ending rather than standing alone." },
        {
          type: "table", caption: "שֶׁל with endings",
          head: ["", "singular", "plural"],
          rows: [
            ["1st", "שֶׁלִּי — my", "שֶׁלָּנוּ — our"],
            ["2nd m.", "שֶׁלְּךָ — your", "שֶׁלָּכֶם — your"],
            ["2nd f.", "שֶׁלָּךְ — your", "שֶׁלָּכֶן — your"],
            ["3rd m.", "שֶׁלּוֹ — his", "שֶׁלָּהֶם — their"],
            ["3rd f.", "שֶׁלָּהּ — her", "שֶׁלָּהֶן — their"],
          ],
        },
        {
          type: "examples", items: [
            { he: "הַבַּיִת שֶׁלִּי", en: "my house" },
            { he: "הַמִּשְׁפָּחָה שֶׁלָּהּ", en: "her family" },
            { he: "הַסְּפָרִים שֶׁלָּנוּ", en: "our books" },
          ],
        },
      ],
      vocab: [
        { he: "שֶׁל", en: "of", translit: "shel" },
        { he: "שֶׁלִּי", en: "my, mine", translit: "sheli" },
        { he: "שֶׁלְּךָ", en: "your (m.)", translit: "shelcha" },
        { he: "שֶׁלָּךְ", en: "your (f.)", translit: "shelach" },
        { he: "שֶׁלּוֹ", en: "his", translit: "shelo" },
        { he: "שֶׁלָּהּ", en: "her", translit: "shela" },
        { he: "שֶׁלָּנוּ", en: "our", translit: "shelanu" },
      ],
      drills: ["vocab", "listen"],
    },
    {
      id: "b2",
      title: "Having",
      titleHe: "יֵשׁ לִי",
      goal: "Say what you have — Hebrew has no verb for it.",
      sections: [
        { type: "text", body: "There is no verb to have. You say there is to me: יֵשׁ לִי, and for the negative אֵין לִי, there isn't to me." },
        {
          type: "examples", items: [
            { he: "יֵשׁ לִי סֵפֶר.", en: "I have a book." },
            { he: "יֵשׁ לָהּ שְׁתֵּי אֲחָיוֹת.", en: "She has two sisters." },
            { he: "אֵין לָנוּ זְמַן.", en: "We don't have time." },
            { he: "יֵשׁ לְךָ דַּקָּה?", en: "Have you got a minute?" },
          ],
        },
        { type: "tip", body: "The thing owned is the grammatical subject, so nothing agrees with the owner. יֵשׁ never changes shape — only the לְ after it does." },
      ],
      vocab: [
        { he: "זְמַן", en: "time", translit: "zman" },
        { he: "כֶּסֶף", en: "money", translit: "kesef" },
        { he: "עֲבוֹדָה", en: "work, job", translit: "avoda" },
        { he: "חָבֵר", en: "friend (m.)", translit: "chaver" },
        { he: "חֲבֵרָה", en: "friend (f.)", translit: "chavera" },
        { he: "אָח", en: "brother", translit: "ach" },
        { he: "אָחוֹת", en: "sister", translit: "achot" },
      ],
      drills: ["vocab", "listen", "build"],
    },
    {
      id: "b3",
      title: "Prepositions that decline",
      titleHe: "נְטִיַּת מִלּוֹת יַחַס",
      goal: "Attach pronoun endings to לְ, בְּ and עִם.",
      sections: [
        { type: "text", body: "Hebrew doesn't say to me — it says the preposition with an ending fused on. You've already used לִי; the others follow the same pattern." },
        {
          type: "table", caption: "Three prepositions, declined",
          head: ["", "לְ — to", "בְּ — in", "עִם — with"],
          rows: [
            ["me", "לִי", "בִּי", "אִתִּי"],
            ["you (m.)", "לְךָ", "בְּךָ", "אִתְּךָ"],
            ["you (f.)", "לָךְ", "בָּךְ", "אִתָּךְ"],
            ["him", "לוֹ", "בּוֹ", "אִתּוֹ"],
            ["her", "לָהּ", "בָּהּ", "אִתָּהּ"],
            ["us", "לָנוּ", "בָּנוּ", "אִתָּנוּ"],
            ["them", "לָהֶם", "בָּהֶם", "אִתָּם"],
          ],
        },
        { type: "tip", body: "עִם is irregular: its declined forms are built on אֶת־, giving אִתִּי rather than עִמִּי. עִמִּי exists, but it's literary." },
      ],
      vocab: [
        { he: "לִי", en: "to me", translit: "li" },
        { he: "לוֹ", en: "to him", translit: "lo" },
        { he: "לָהּ", en: "to her", translit: "la" },
        { he: "אִתִּי", en: "with me", translit: "iti" },
        { he: "אִתּוֹ", en: "with him", translit: "ito" },
        { he: "עָלַי", en: "on me, about me", translit: "alai" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "“With her” is —", options: ["אִתָּהּ", "עִמָּהּ בְּ", "לָהּ", "בָּהּ"], correct: 0, why: "עִם declines on the stem אִת־. לָהּ is to her, בָּהּ is in her." },
      ],
    },
    {
      id: "b4",
      title: "The word with no meaning",
      titleHe: "אֶת",
      goal: "Use אֶת before a definite direct object.",
      sections: [
        { type: "text", body: "אֶת has no translation. It marks the direct object of a verb — but only when that object is definite. It's one of the commonest words in Hebrew and one of the last a learner uses correctly." },
        {
          type: "examples", items: [
            { he: "אֲנִי רוֹאֶה בַּיִת.", en: "I see a house. — no אֶת" },
            { he: "אֲנִי רוֹאֶה אֶת הַבַּיִת.", en: "I see the house. — definite, so אֶת" },
            { he: "הִיא אוֹהֶבֶת אֶת דָּוִד.", en: "She loves David. — names are definite" },
          ],
        },
        { type: "text", body: "With a pronoun it declines, and those forms are how you say me, him, them as objects." },
        {
          type: "table", caption: "אֶת with endings",
          head: ["", "form"],
          rows: [
            ["me", "אוֹתִי"], ["you (m.)", "אוֹתְךָ"], ["you (f.)", "אוֹתָךְ"],
            ["him / it", "אוֹתוֹ"], ["her", "אוֹתָהּ"], ["us", "אוֹתָנוּ"], ["them", "אוֹתָם"],
          ],
        },
      ],
      vocab: [
        { he: "אֶת", en: "(marks a definite object)", translit: "et" },
        { he: "אוֹתִי", en: "me", translit: "oti" },
        { he: "אוֹתוֹ", en: "him, it", translit: "oto" },
        { he: "אוֹתָהּ", en: "her", translit: "ota" },
        { he: "רוֹאֶה", en: "sees", translit: "ro'e" },
        { he: "שׁוֹמֵעַ", en: "hears", translit: "shome'a" },
        { he: "יוֹדֵעַ", en: "knows", translit: "yode'a" },
      ],
      drills: ["vocab", "et"],
      extra: [
        { type: "choice", q: "Which sentence needs אֶת?", options: ["I'm reading the book", "I'm reading a book", "I'm reading", "I read well"], correct: 0, why: "אֶת appears only before a definite direct object — the book, not a book." },
      ],
    },
    {
      id: "b5",
      title: "What happened",
      titleHe: "זְמַן עָבָר",
      goal: "Use the past tense of pa'al, where every person has its own ending.",
      sections: [
        { type: "text", body: "Unlike the present, the past marks person as well as gender — nine endings, hung on a stem that stays put. Because the ending already says who, the pronoun is often dropped: כָּתַבְתִּי on its own means I wrote." },
        { type: "binyan", id: "paal", tense: "past" },
        { type: "tip", body: "The third person masculine singular — כָּתַב — has no ending at all. That bare form is the dictionary form of every Hebrew verb, which is why dictionaries list wrote rather than to write." },
        {
          type: "examples", items: [
            { he: "אֶתְמוֹל קָרָאתִי סֵפֶר.", en: "Yesterday I read a book." },
            { he: "הֵם לָמְדוּ עִבְרִית.", en: "They studied Hebrew." },
            { he: "לֹא שָׁמַעְתִּי.", en: "I didn't hear." },
          ],
        },
      ],
      vocab: [
        { he: "אֶתְמוֹל", en: "yesterday", translit: "etmol" },
        { he: "הָיָה", en: "was (m.)", translit: "haya" },
        { he: "הָיְתָה", en: "was (f.)", translit: "hayta" },
        { he: "אָמַר", en: "said", translit: "amar" },
        { he: "בָּא", en: "came", translit: "ba" },
        { he: "הָלַךְ", en: "went", translit: "halach" },
        { he: "נָתַן", en: "gave", translit: "natan" },
      ],
      drills: ["vocab", "conjugate:paal:past"],
    },
    {
      id: "b6",
      title: "Days and hours",
      titleHe: "זְמַן",
      goal: "Name the days, ask the time, and place things in the week.",
      sections: [
        { type: "text", body: "Hebrew days are numbered, not named — Sunday is day one. Only Saturday has a name of its own." },
        {
          type: "table", caption: "The week",
          head: ["day", "Hebrew"],
          rows: [
            ["Sunday", "יוֹם רִאשׁוֹן"], ["Monday", "יוֹם שֵׁנִי"], ["Tuesday", "יוֹם שְׁלִישִׁי"],
            ["Wednesday", "יוֹם רְבִיעִי"], ["Thursday", "יוֹם חֲמִישִׁי"], ["Friday", "יוֹם שִׁישִׁי"],
            ["Saturday", "שַׁבָּת"],
          ],
        },
        {
          type: "examples", items: [
            { he: "מָה הַשָּׁעָה?", en: "What time is it?" },
            { he: "בְּשָׁעָה שֶׁבַע.", en: "At seven o'clock." },
            { he: "בַּבֹּקֶר, בָּעֶרֶב", en: "in the morning, in the evening" },
          ],
        },
      ],
      vocab: [
        { he: "יוֹם", en: "day", translit: "yom" },
        { he: "שָׁבוּעַ", en: "week", translit: "shavua" },
        { he: "חֹדֶשׁ", en: "month", translit: "chodesh" },
        { he: "שָׁעָה", en: "hour, o'clock", translit: "sha'a" },
        { he: "דַּקָּה", en: "minute", translit: "daka" },
        { he: "בֹּקֶר", en: "morning", translit: "boker" },
        { he: "עֶרֶב", en: "evening", translit: "erev" },
        { he: "לַיְלָה", en: "night", translit: "layla" },
        { he: "מָחָר", en: "tomorrow", translit: "machar" },
      ],
      drills: ["vocab", "listen"],
    },
    {
      id: "b7",
      title: "Two nouns, one idea",
      titleHe: "סְמִיכוּת",
      goal: "Read and build construct chains — Hebrew's compound noun.",
      sections: [
        { type: "text", body: "To join two nouns, Hebrew puts them side by side. The first one carries the meaning of of and often changes shape to do it: בַּיִת house plus סֵפֶר book gives בֵּית סֵפֶר, a school." },
        {
          type: "table", caption: "The first noun shortens",
          head: ["alone", "in a chain"],
          rows: [
            ["בַּיִת — house", "בֵּית סֵפֶר — school"],
            ["בַּיִת — house", "בֵּית חוֹלִים — hospital"],
            ["מִשְׁפָּחָה — family", "מִשְׁפַּחַת כֹּהֵן — the Cohen family"],
            ["עוּגָה — cake", "עוּגַת שׁוֹקוֹלָד — chocolate cake"],
          ],
        },
        { type: "tip", body: "The article goes on the second word, never the first: בֵּית הַסֵּפֶר is the school. Writing הַבֵּית סֵפֶר is the classic mistake." },
        { type: "tip", body: "In the plural it's the first noun that pluralises, because it's the one being counted: בָּתֵּי סֵפֶר, schools." },
      ],
      vocab: [
        { he: "בֵּית סֵפֶר", en: "school", translit: "beit sefer" },
        { he: "בֵּית חוֹלִים", en: "hospital", translit: "beit cholim" },
        { he: "בֵּית כְּנֶסֶת", en: "synagogue", translit: "beit knesset" },
        { he: "עוֹרֵךְ דִּין", en: "lawyer", translit: "orech din" },
        { he: "כַּדּוּרֶגֶל", en: "football", translit: "kaduregel" },
        { he: "יוֹם הֻלֶּדֶת", en: "birthday", translit: "yom huledet" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "“The school” is —", options: ["בֵּית הַסֵּפֶר", "הַבֵּית סֵפֶר", "הַבֵּית הַסֵּפֶר", "בֵּית סֵפֶר הַ"], correct: 0, why: "In a construct chain the article attaches to the second noun only." },
      ],
    },
    {
      id: "b8",
      title: "The second binyan",
      titleHe: "בִּנְיַן פִּעֵל",
      goal: "Recognise and use pi'el, the pattern with a doubled middle letter.",
      sections: [
        { type: "text", body: "Every Hebrew verb belongs to a binyan — a pattern the three root letters are poured into. You've been using פָּעַל all along. פִּעֵל is the second, and you can spot it: the present tense starts with מְ, and the middle root letter carries a dagesh." },
        { type: "binyan", id: "piel", tense: "present" },
        { type: "binyan", id: "piel", tense: "past" },
        { type: "tip", body: "Same root, different binyan, different meaning. From ל־מ־ד: לוֹמֵד in pa'al is learns, מְלַמֵּד in pi'el is teaches — makes someone learn." },
      ],
      vocab: [
        { he: "מְדַבֵּר", en: "speaks", translit: "medaber" },
        { he: "מְלַמֵּד", en: "teaches", translit: "melamed" },
        { he: "מְסַפֵּר", en: "tells", translit: "mesaper" },
        { he: "מְבַקֵּשׁ", en: "asks for", translit: "mevakesh" },
        { he: "מְקַבֵּל", en: "receives, gets", translit: "mekabel" },
        { he: "מְשַׂחֵק", en: "plays", translit: "mesachek" },
        { he: "מְטַיֵּל", en: "travels, strolls", translit: "metayel" },
      ],
      drills: ["vocab", "conjugate:piel:present"],
    },
    {
      id: "b9",
      title: "Saying no",
      titleHe: "שְׁלִילָה",
      goal: "Negate a verb, an existence, and a whole idea.",
      sections: [
        { type: "text", body: "לֹא goes before the verb and negates it. אֵין negates existence. They aren't interchangeable: אֲנִי לֹא רוֹאֶה is I don't see, but אֵין סֵפֶר is there's no book." },
        {
          type: "examples", items: [
            { he: "אֲנִי לֹא יוֹדֵעַ.", en: "I don't know." },
            { he: "אֵין לִי כֶּסֶף.", en: "I have no money." },
            { he: "אַף אֶחָד לֹא בָּא.", en: "Nobody came." },
            { he: "אַף פַּעַם לֹא הָיִיתִי שָׁם.", en: "I've never been there." },
          ],
        },
        { type: "tip", body: "Hebrew doubles its negatives and means it. אַף אֶחָד לֹא בָּא is literally nobody didn't come, and means nobody came. Dropping the לֹא is wrong." },
      ],
      vocab: [
        { he: "לֹא", en: "no, not", translit: "lo" },
        { he: "אַף אֶחָד", en: "nobody", translit: "af echad" },
        { he: "אַף פַּעַם", en: "never", translit: "af pa'am" },
        { he: "כְּלוּם", en: "nothing", translit: "klum" },
        { he: "עֲדַיִן לֹא", en: "not yet", translit: "adayin lo" },
        { he: "רַק", en: "only", translit: "rak" },
      ],
      drills: ["vocab", "listen"],
      extra: [
        { type: "choice", q: "“Nobody came” —", options: ["אַף אֶחָד לֹא בָּא", "אַף אֶחָד בָּא", "לֹא אַף אֶחָד בָּא", "אֵין אֶחָד בָּא"], correct: 0, why: "The negative word and לֹא both appear; Hebrew requires the double negative." },
      ],
    },
  ],
};
