/* Level 4 — הַפֹּעַל · The verb system.

   This is the level where Hebrew stops being a vocabulary problem. Seven
   patterns, three tenses, and a root system that lets you guess at a word
   you've never seen — which is the point at which reading a real book starts
   to work. */

export default {
  level: 4,
  name: "The verb system",
  nameHe: "הַפֹּעַל",
  blurb: "The future, the infinitive, and the seven binyanim — the machinery that makes Hebrew guessable.",
  lessons: [
    {
      id: "v1",
      title: "What will happen",
      titleHe: "זְמַן עָתִיד",
      goal: "Use the future of pa'al, where the person is a prefix rather than an ending.",
      sections: [
        { type: "text", body: "The past hangs its person on the end of the word. The future puts it on the front — א for I, ת for you and she, י for he, נ for we. Once you know those four letters you can read any future verb's person off its first letter." },
        { type: "binyan", id: "paal", tense: "future" },
        { type: "tip", body: "ת does double duty: תִּכְתֹּב is both you (m.) will write and she will write. Only context or a pronoun tells them apart." },
        {
          type: "examples", items: [
            { he: "מָחָר אֶכְתֹּב מִכְתָּב.", en: "Tomorrow I'll write a letter." },
            { he: "מָתַי תָּבוֹא?", en: "When will you come?" },
            { he: "נִרְאֶה.", en: "We'll see." },
          ],
        },
      ],
      vocab: [
        { he: "מִכְתָּב", en: "letter", translit: "michtav" },
        { he: "אוּלַי", en: "maybe", translit: "ulai" },
        { he: "בְּוַדַּאי", en: "certainly", translit: "bevadai" },
        { he: "אַחַר כָּךְ", en: "afterwards", translit: "achar kach" },
        { he: "עוֹד", en: "more, still, another", translit: "od" },
      ],
      drills: ["vocab", "conjugate:paal:future"],
    },
    {
      id: "v2",
      title: "To do something",
      titleHe: "שֵׁם הַפֹּעַל",
      goal: "Form and use the infinitive.",
      sections: [
        { type: "text", body: "The infinitive begins with לְ and doesn't change for person, gender or number. It's what follows verbs like want, can and must — and what you'll look up in a modern dictionary." },
        {
          type: "table", caption: "Infinitives by binyan",
          head: ["binyan", "infinitive"],
          rows: [
            ["פָּעַל", "לִכְתֹּב — to write"],
            ["פִּעֵל", "לְדַבֵּר — to speak"],
            ["הִפְעִיל", "לְהַסְבִּיר — to explain"],
            ["נִפְעַל", "לְהִכָּנֵס — to enter"],
            ["הִתְפַּעֵל", "לְהִתְלַבֵּשׁ — to get dressed"],
          ],
        },
        {
          type: "examples", items: [
            { he: "אֲנִי רוֹצֶה לִלְמֹד.", en: "I want to learn." },
            { he: "אֶפְשָׁר לְדַבֵּר אִתְּךָ?", en: "Can I talk to you?" },
            { he: "צָרִיךְ לָלֶכֶת.", en: "One has to go. / We should go." },
          ],
        },
        { type: "tip", body: "צָרִיךְ must, אֶפְשָׁר it's possible and אָסוּר it's forbidden aren't verbs — they're words that take an infinitive, and they don't conjugate for tense at all." },
      ],
      vocab: [
        { he: "לִלְמֹד", en: "to learn", translit: "lilmod" },
        { he: "לָלֶכֶת", en: "to go", translit: "lalechet" },
        { he: "לָבוֹא", en: "to come", translit: "lavo" },
        { he: "לֶאֱכֹל", en: "to eat", translit: "le'echol" },
        { he: "לָתֵת", en: "to give", translit: "latet" },
        { he: "צָרִיךְ", en: "must, need to", translit: "tsarich" },
        { he: "אֶפְשָׁר", en: "it's possible", translit: "efshar" },
        { he: "יָכוֹל", en: "can, is able", translit: "yachol" },
      ],
      drills: ["vocab", "build"],
    },
    {
      id: "v9",
      title: "You have to, you can, you mustn't",
      titleHe: "מִשְׁפָּט סְתָמִי",
      goal: "Build the sentences that have no subject and no conjugated verb.",
      sections: [
        { type: "text", body: "A large family of everyday Hebrew sentences has no subject at all and no verb in any tense. It is one word — צָרִיךְ, אֶפְשָׁר, אָסוּר — followed by the infinitive you have just learned." },
        {
          type: "table", caption: "The words that carry these sentences",
          head: ["meaning", "agrees with a person?", "Hebrew"],
          rows: [
            ["needs to, must", "yes — צְרִיכָה, צְרִיכִים", "צָרִיךְ"],
            ["can, is able to", "yes — יְכוֹלָה, יְכוֹלִים", "יָכוֹל"],
            ["obliged to, must", "yes — חַיֶּבֶת, חַיָּבִים", "חַיָּב"],
            ["it is possible, one may", "no — never changes", "אֶפְשָׁר"],
            ["it is permitted", "no — never changes", "מֻתָּר"],
            ["it is forbidden", "no — never changes", "אָסוּר"],
            ["it is worth it", "no — never changes", "כְּדַאי"],
            ["it is hard to", "no — never changes", "קָשֶׁה"],
          ],
        },
        { type: "text", body: "The split in that last column is the whole grammar of the lesson. צָרִיךְ, יָכוֹל and חַיָּב describe a person, so they agree with that person. אֶפְשָׁר, מֻתָּר, אָסוּר and כְּדַאי describe the situation, so there is nobody for them to agree with and they never move." },
        {
          type: "examples", items: [
            { he: "אֲנִי צָרִיךְ לָלֶכֶת.", en: "I have to go." },
            { he: "הִיא צְרִיכָה לַעֲבֹד מָחָר.", en: "She has to work tomorrow." },
            { he: "אֶפְשָׁר לִשְׁאֹל שְׁאֵלָה?", en: "May I ask a question?" },
            { he: "אָסוּר לְעַשֵּׁן כָּאן.", en: "Smoking is forbidden here." },
            { he: "כְּדַאי לְךָ לָבוֹא מָחָר.", en: "It's worth your while to come tomorrow." },
          ],
        },
        { type: "tip", body: "To say who a subjectless sentence is about, add לְ with an ending: כְּדַאי לְךָ, אָסוּר לָהֶם, קָשֶׁה לִי. The sentence still has no grammatical subject — the person arrives as an indirect object." },
        { type: "tip", body: "The negative of אֶפְשָׁר is not לֹא אֶפְשָׁר but אִי אֶפְשָׁר. That אִי־ is a prefix meaning un-, and it turns up on other words too: אִי־הֲבָנָה, a misunderstanding." },
      ],
      vocab: [
        { he: "מֻתָּר", en: "it is permitted", translit: "mutar" },
        { he: "אָסוּר", en: "it is forbidden", translit: "asur" },
        { he: "כְּדַאי", en: "it is worth it", translit: "kedai" },
        { he: "חַיָּב", en: "obliged, must", translit: "chayav" },
        { he: "אִי אֶפְשָׁר", en: "it is impossible", translit: "i efshar" },
        { he: "צְרִיכָה", en: "needs to (f.)", translit: "tsricha" },
        { he: "רַשַּׁאי", en: "entitled to, allowed to", translit: "rashai" },
      ],
      drills: ["vocab", "modal", "build"],
    },
    {
      id: "v3",
      title: "Making it happen",
      titleHe: "בִּנְיַן הִפְעִיל",
      goal: "Recognise hif'il and its causative sense.",
      sections: [
        { type: "text", body: "הִפְעִיל usually means causing the action rather than doing it. Its present begins with מַ and has a long i in the middle; its past begins with הִ." },
        { type: "binyan", id: "hifil", tense: "present" },
        { type: "binyan", id: "hifil", tense: "past" },
        { type: "tip", body: "The causative link is often visible across binyanim on one root. From ל־ב־ש: לוֹבֵשׁ wears, מַלְבִּישׁ dresses someone else, מִתְלַבֵּשׁ gets dressed." },
      ],
      vocab: [
        { he: "מַסְבִּיר", en: "explains", translit: "masbir" },
        { he: "מַתְחִיל", en: "begins", translit: "matchil" },
        { he: "מַרְגִּישׁ", en: "feels", translit: "margish" },
        { he: "מַזְמִין", en: "invites, orders", translit: "mazmin" },
        { he: "מַכִּיר", en: "knows, is acquainted with", translit: "makir" },
        { he: "מַחְלִיט", en: "decides", translit: "machlit" },
      ],
      drills: ["vocab", "conjugate:hifil:present", "binyan-id"],
    },
    {
      id: "v4",
      title: "Having it happen to you",
      titleHe: "בִּנְיַן נִפְעַל",
      goal: "Recognise nif'al, the passive counterpart of pa'al.",
      sections: [
        { type: "text", body: "נִפְעַל is what pa'al becomes when the subject is on the receiving end. Its present and past both begin with נִ, which makes it the easiest binyan to spot — and the easiest to confuse with itself, since נִכְנַס is both he entered and he enters." },
        { type: "binyan", id: "nifal", tense: "present" },
        { type: "binyan", id: "nifal", tense: "past" },
        { type: "tip", body: "Many nif'al verbs aren't passive in meaning at all — נִכְנָס enters, נִשְׁאָר stays, נִמְצָא is located. Treat the pattern as a shape first and a meaning second." },
      ],
      vocab: [
        { he: "נִכְנָס", en: "enters", translit: "nichnas" },
        { he: "נִמְצָא", en: "is located, is found", translit: "nimtsa" },
        { he: "נִשְׁאָר", en: "stays, remains", translit: "nish'ar" },
        { he: "נִרְאֶה", en: "seems, looks", translit: "nir'e" },
        { he: "נִגְמַר", en: "is finished", translit: "nigmar" },
        { he: "נוֹלַד", en: "was born", translit: "nolad" },
      ],
      drills: ["vocab", "binyan-id"],
    },
    {
      id: "v5",
      title: "Doing it to yourself",
      titleHe: "בִּנְיַן הִתְפַּעֵל",
      goal: "Recognise hitpa'el — and the letter-swap that hides it.",
      sections: [
        { type: "text", body: "הִתְפַּעֵל is reflexive: the action comes back on whoever does it. Present begins מִתְ, past begins הִתְ." },
        { type: "binyan", id: "hitpael", tense: "present" },
        { type: "text", body: "When the root starts with a hissing letter — ס, שׂ, שׁ, צ, ז — that letter swaps places with the ת, because the two are awkward to say in the other order." },
        {
          type: "table", caption: "The swap",
          head: ["expected", "actual", "meaning"],
          rows: [
            ["מִתְסַכֵּל", "מִסְתַּכֵּל", "looks at"],
            ["מִתְשַׁמֵּשׁ", "מִשְׁתַּמֵּשׁ", "uses"],
            ["מִתְצַעֵר", "מִצְטַעֵר", "is sorry"],
          ],
        },
        { type: "tip", body: "With צ the ת also hardens to ט — מִצְטַעֵר, not מִצְתַּעֵר. It's the one form worth memorising outright, because מִצְטַעֵר is how you apologise." },
      ],
      vocab: [
        { he: "מִתְלַבֵּשׁ", en: "gets dressed", translit: "mitlabesh" },
        { he: "מִתְעוֹרֵר", en: "wakes up", translit: "mit'orer" },
        { he: "מִסְתַּכֵּל", en: "looks at", translit: "mistakel" },
        { he: "מִשְׁתַּמֵּשׁ", en: "uses", translit: "mishtamesh" },
        { he: "מִצְטַעֵר", en: "is sorry", translit: "mitsta'er" },
        { he: "מִתְגַּעְגֵּעַ", en: "misses, longs for", translit: "mitga'age'a" },
      ],
      drills: ["vocab", "binyan-id"],
      extra: [
        { type: "choice", q: "Why is it מִשְׁתַּמֵּשׁ and not מִתְשַׁמֵּשׁ?", options: ["The ש and the ת swap places", "It's an unrelated irregular verb", "The root has four letters", "It's a different binyan"], correct: 0, why: "Roots beginning with a sibilant swap that letter with the ת of the prefix." },
      ],
    },
    {
      id: "v10",
      title: "The future everywhere else",
      titleHe: "עָתִיד בְּכָל הַבִּנְיָנִים",
      goal: "Read the future of pi'el, hif'il and hitpa'el — same four prefixes, different stem.",
      sections: [
        { type: "text", body: "The future you learned for pa'al was not a fact about pa'al. Every binyan builds its future the same way: א for I, נ for we, ת for you and for she, י for he and for they. What differs is the stem those letters are stuck to, and the vowel underneath them." },
        {
          type: "table", caption: "He will — one root per binyan",
          head: ["binyan", "the tell", "he will"],
          rows: [
            ["פָּעַל — write", "יִ־ and a bare stem", "יִכְתֹּב"],
            ["פִּעֵל — speak", "יְ־ with a shva", "יְדַבֵּר"],
            ["הִפְעִיל — explain", "יַ־ with a patach", "יַסְבִּיר"],
            ["נִפְעַל — enter", "יִ־ and a dagesh in the first root letter", "יִכָּנֵס"],
            ["הִתְפַּעֵל — get dressed", "the ־תְ of hitpa'el survives", "יִתְלַבֵּשׁ"],
          ],
        },
        { type: "text", body: "The prefix vowel is the fastest way to identify a verb you have never seen. יְ־ is pi'el, יַ־ is hif'il, and the הִת of hitpa'el is unmistakable in any tense." },
        { type: "binyan", id: "piel", tense: "future" },
        { type: "binyan", id: "hifil", tense: "future" },
        { type: "binyan", id: "hitpael", tense: "future" },
        { type: "tip", body: "Two cells always collide: תְּ־ is both you (m. sing.) and she. הִיא תְּדַבֵּר and אַתָּה תְּדַבֵּר are the same word, and only the pronoun or the context tells them apart. Hebrew has lived with this for three thousand years; you will too." },
        { type: "tip", body: "In speech the plural feminine forms have gone. Nobody says תְּדַבֵּרְנָה — they say תְּדַבְּרוּ for everyone. You will still meet the old forms in print, which is why the tables carry them." },
      ],
      vocab: [
        { he: "יְדַבֵּר", en: "he will speak", translit: "yedaber" },
        { he: "יַסְבִּיר", en: "he will explain", translit: "yasbir" },
        { he: "יִכָּנֵס", en: "he will go in", translit: "yikanes" },
        { he: "יִתְלַבֵּשׁ", en: "he will get dressed", translit: "yitlabesh" },
        { he: "נְדַבֵּר", en: "we will speak", translit: "nedaber" },
        { he: "אַסְבִּיר", en: "I will explain", translit: "asbir" },
      ],
      drills: ["conjugate:piel:future", "conjugate:hifil:future", "conjugate:hitpael:future", "vocab"],
    },
    {
      id: "v6",
      title: "The two passives",
      titleHe: "פֻּעַל וְהֻפְעַל",
      goal: "Recognise pu'al and huf'al on the page.",
      sections: [
        { type: "text", body: "Two binyanim exist only as passives: פֻּעַל is the passive of pi'el, הֻפְעַל the passive of hif'il. Neither has an infinitive or an imperative, and outside the third person they're rare — so this is a recognition lesson, not a production one." },
        { type: "passives" },
        { type: "tip", body: "Look for the u vowel where you'd expect a or i. מְדַבֵּר speaks becomes מְדֻבָּר is spoken of; מַסְבִּיר explains becomes מֻסְבָּר is explained." },
      ],
      vocab: [
        { he: "מְדֻבָּר", en: "spoken of, in question", translit: "meduba r" },
        { he: "מֻסְבָּר", en: "explained", translit: "musbar" },
        { he: "מְקֻבָּל", en: "accepted, customary", translit: "mekubal" },
        { he: "מֻכָּן", en: "ready, prepared", translit: "muchan" },
        { he: "מְסֻדָּר", en: "arranged, tidy", translit: "mesudar" },
      ],
      drills: ["vocab"],
    },
    {
      id: "v11",
      title: "Written, closed, known",
      titleHe: "בֵּינוֹנִי פָּעוּל",
      goal: "Read the פָּעוּל form — the state an action leaves a thing in.",
      sections: [
        { type: "text", body: "Beside the two passive binyanim there is a much simpler form, and it is far commoner than either: פָּעוּל. It is built straight off a pa'al root, it behaves like an adjective, and it names the state something has been left in." },
        {
          type: "table", caption: "The verb, and the state it leaves behind",
          head: ["verb", "state"],
          rows: [
            ["כָּתַב — wrote", "כָּתוּב — written"],
            ["פָּתַח — opened", "פָּתוּחַ — open"],
            ["סָגַר — closed", "סָגוּר — closed, shut"],
            ["יָדַע — knew", "יָדוּעַ — known"],
            ["שָׁבַר — broke", "שָׁבוּר — broken"],
            ["אָהַב — loved", "אָהוּב — beloved"],
            ["מָכַר — sold", "מָכוּר — sold"],
          ],
        },
        { type: "text", body: "It agrees like any adjective — כְּתוּבָה, פְּתוּחִים, סְגוּרוֹת — and it sits after its noun in the same place an adjective would." },
        {
          type: "examples", items: [
            { he: "הַחֲנוּת סְגוּרָה.", en: "The shop is closed." },
            { he: "הַחַלּוֹן פָּתוּחַ.", en: "The window is open." },
            { he: "זֶה כָּתוּב בַּסֵּפֶר.", en: "It's written in the book." },
            { he: "הַסִּפּוּר הַזֶּה יָדוּעַ.", en: "This story is well known." },
          ],
        },
        { type: "tip", body: "This is not the past tense, and the difference matters. הַחֲנוּת סְגוּרָה says the shop is shut now; הַחֲנוּת נִסְגְּרָה says somebody shut it. One is a state, the other an event." },
        { type: "tip", body: "Some have drifted so far from their verb that nobody hears one behind them any more: עָשׂוּי מֵעֵץ, made of wood, is a sentence about a table rather than about anybody making it. At that point the dictionary stops calling it a verb form and simply lists it as an adjective." },
      ],
      vocab: [
        { he: "כָּתוּב", en: "written", translit: "katuv" },
        { he: "פָּתוּחַ", en: "open", translit: "patuach" },
        { he: "סָגוּר", en: "closed", translit: "sagur" },
        { he: "שָׁבוּר", en: "broken", translit: "shavur" },
        { he: "יָדוּעַ", en: "known", translit: "yadua" },
        { he: "אָהוּב", en: "beloved", translit: "ahuv" },
        { he: "עָשׂוּי", en: "made of, likely to", translit: "asuy" },
      ],
      drills: ["vocab", "pauul", "cloze"],
    },
    {
      id: "v7",
      title: "Telling someone to do it",
      titleHe: "צִוּוּי",
      goal: "Give an order — the textbook way and the way people actually speak.",
      sections: [
        { type: "text", body: "There is a proper imperative, and it's what you'll read in books and signs." },
        {
          type: "table", caption: "Imperatives",
          head: ["binyan", "to a man", "to a woman", "to a group"],
          rows: [
            ["פָּעַל — write", "כְּתֹב", "כִּתְבִי", "כִּתְבוּ"],
            ["פִּעֵל — speak", "דַּבֵּר", "דַּבְּרִי", "דַּבְּרוּ"],
            ["הִפְעִיל — explain", "הַסְבֵּר", "הַסְבִּירִי", "הַסְבִּירוּ"],
          ],
        },
        { type: "text", body: "In speech, Israelis mostly use the future tense instead, which sounds softer: תִּכְתֹּב rather than כְּתֹב." },
        { type: "tip", body: "The negative imperative has no choice — it is always אַל plus the future. אַל תֵּלֵךְ, don't go. לֹא תֵּלֵךְ is not a command; it means you will not go." },
      ],
      vocab: [
        { he: "בּוֹא", en: "come! (m.)", translit: "bo" },
        { he: "בּוֹאִי", en: "come! (f.)", translit: "bo'i" },
        { he: "תֵּן", en: "give! (m.)", translit: "ten" },
        { he: "סְלִיחָה", en: "excuse me, sorry", translit: "slicha" },
        { he: "אַל", en: "don't (with the future)", translit: "al" },
        { he: "חַכֵּה", en: "wait! (m.)", translit: "chake" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "“Don't go” (to a man) is —", options: ["אַל תֵּלֵךְ", "לֹא תֵּלֵךְ", "אַל הָלַךְ", "לֹא לֵךְ"], correct: 0, why: "Negative commands use אַל with the future. לֹא תֵּלֵךְ is a prediction, not an order." },
      ],
    },
    {
      id: "v8",
      title: "Roots that misbehave",
      titleHe: "גְּזָרוֹת",
      goal: "Read verbs whose roots contain נ, ו or ה and don't follow the tables.",
      sections: [
        { type: "text", body: "The tables you've learned describe strong roots — three solid consonants. Some roots contain a letter that won't stay put, and those are among the commonest verbs in the language, so they have to be met head-on." },
        { type: "weak", id: "pe-nun" },
        { type: "weak", id: "ayin-vav" },
        { type: "weak", id: "lamed-he" },
        { type: "tip", body: "Don't memorise rules for these. Learn the handful of frequent verbs in each family as words, and the pattern will settle by itself." },
      ],
      vocab: [
        { he: "נוֹפֵל", en: "falls", translit: "nofel" },
        { he: "נוֹסֵעַ", en: "travels", translit: "nose'a" },
        { he: "קָם", en: "gets up", translit: "kam" },
        { he: "שָׁר", en: "sings", translit: "shar" },
        { he: "קוֹנֶה", en: "buys", translit: "kone" },
        { he: "רוֹאֶה", en: "sees", translit: "ro'e" },
        { he: "עוֹשֶׂה", en: "does, makes", translit: "ose" },
      ],
      drills: ["vocab", "weak"],
    },
    {
      id: "v12",
      title: "The preposition the verb wants",
      titleHe: "פֹּעַל וּמִלַּת יַחַס",
      goal: "Learn verbs together with the preposition they take — because it is rarely English's.",
      sections: [
        { type: "text", body: "A Hebrew verb usually arrives welded to one particular preposition, and knowing the verb without it gets you a sentence nobody says. You do not wait to someone in English, but Hebrew waits לְ. Learn the pair as one item." },
        {
          type: "table", caption: "Verbs and their prepositions",
          head: ["English", "Hebrew"],
          rows: [
            ["to help someone", "עָזַר לְ־"],
            ["to wait for", "חִכָּה לְ־"],
            ["to answer someone", "עָנָה לְ־"],
            ["to look at", "הִסְתַּכֵּל עַל"],
            ["to tell about", "סִפֵּר עַל"],
            ["to give up on", "וִתֵּר עַל"],
            ["to ask someone for", "בִּקֵּשׁ מִ־"],
            ["to use", "הִשְׁתַּמֵּשׁ בְּ־"],
            ["to believe in", "הֶאֱמִין בְּ־"],
            ["to be interested in", "הִתְעַנְיֵן בְּ־"],
            ["to go into", "נִכְנַס לְ־"],
            ["to go out of", "יָצָא מִ־"],
            ["to get married to", "הִתְחַתֵּן עִם"],
            ["to meet someone", "פָּגַשׁ אֶת"],
          ],
        },
        { type: "text", body: "Once the preposition is chosen, it declines: whatever pronoun follows the verb is fused onto the preposition rather than standing on its own." },
        {
          type: "examples", items: [
            { he: "חִכִּיתִי לוֹ שָׁעָה.", en: "I waited an hour for him." },
            { he: "הִיא עָזְרָה לִי מְאוֹד.", en: "She helped me a great deal." },
            { he: "הִסְתַּכַּלְתִּי עָלֶיהָ.", en: "I looked at her." },
            { he: "הִשְׁתַּמַּשְׁתִּי בּוֹ.", en: "I used it." },
            { he: "סִפַּרְתִּי לָהֶם עַל הַסֵּפֶר.", en: "I told them about the book." },
          ],
        },
        { type: "tip", body: "That last example carries both at once: סִפֵּר takes לְ for the person told and עַל for the thing told about. Verbs with two prepositions are common, and the order is fixed — person first." },
        { type: "tip", body: "A dictionary entry that reads עָזַר לְ־ is not being sloppy about where the entry ends. The dash is the entry. Copy it into your notes with the preposition attached and you will never have to unlearn it." },
      ],
      vocab: [
        { he: "עָזַר לְ", en: "helped (someone)", translit: "azar le" },
        { he: "חִכָּה לְ", en: "waited for", translit: "chika le" },
        { he: "הִסְתַּכֵּל עַל", en: "looked at", translit: "histakel al" },
        { he: "הִשְׁתַּמֵּשׁ בְּ", en: "used", translit: "hishtamesh be" },
        { he: "הֶאֱמִין בְּ", en: "believed in", translit: "he'emin be" },
        { he: "וִתֵּר עַל", en: "gave up on", translit: "viter al" },
        { he: "הִתְחַתֵּן עִם", en: "married", translit: "hitchaten im" },
        { he: "הִתְעַנְיֵן בְּ", en: "took an interest in", translit: "hit'anyen be" },
      ],
      drills: ["vocab", "preposition", "cloze"],
    },
    {
      id: "v13",
      title: "Three more families that misbehave",
      titleHe: "עוֹד גְּזָרוֹת",
      goal: "Read roots that begin with י, end with א, or end with a guttural.",
      sections: [
        { type: "text", body: "The three families in the last lesson cover most of what goes wrong. These three cover nearly all the rest — and between them they account for a startling share of the commonest verbs in the language." },
        { type: "weak", id: "pe-yod" },
        { type: "weak", id: "lamed-alef" },
        { type: "weak", id: "lamed-guttural" },
        { type: "tip", body: "None of these is irregular in the English sense. Each is the ordinary pattern bending around a letter that will not take the vowel the pattern asks for — ע and ח will not close a syllable on anything but an a, א stops being pronounced at all, and a י at the head of a word turns into a vowel. Knowing which letter is causing the trouble is most of reading the form." },
        { type: "text", body: "That is the last of the grammar the verb system needs. What remains is the habit of looking at an unfamiliar verb and asking three questions in order: which three letters are the root, which binyan is this shape, and which tense are those prefixes." },
      ],
      vocab: [
        { he: "לָשֶׁבֶת", en: "to sit, to live somewhere", translit: "lashevet" },
        { he: "יֵשֵׁב", en: "he will sit", translit: "yeshev" },
        { he: "לָדַעַת", en: "to know", translit: "lada'at" },
        { he: "מָצָא", en: "he found", translit: "matsa" },
        { he: "לִמְצֹא", en: "to find", translit: "limtso" },
        { he: "לִשְׁמֹעַ", en: "to hear", translit: "lishmo'a" },
        { he: "יִשְׁמַע", en: "he will hear", translit: "yishma" },
      ],
      drills: ["vocab", "weak"],
    },
  ],
};
