/* Level 2 — אוּלְפָּן א׳ · First sentences.

   The order here is the one every ulpan uses, and it is not the order a
   frequency list would give: gender before plurals because plurals depend on
   it, the article before adjectives because adjectives have to agree with it,
   and the present tense last, once there are nouns for it to act on. */

export default {
  level: 2,
  name: "Ulpan Alef",
  nameHe: "אוּלְפָּן א׳",
  blurb: "Nouns, adjectives, the present tense — enough Hebrew to say what is where and who is doing what.",
  lessons: [
    {
      id: "a1",
      title: "Hello, and who you are",
      titleHe: "שָׁלוֹם",
      goal: "Greet someone and name yourself and them.",
      sections: [
        { type: "text", body: "Hebrew separates you (m.) from you (f.) — there is no neutral second person. Which one you use depends on who you're speaking to, and you'll be choosing between them in every sentence from here on." },
        {
          type: "table", caption: "Pronouns",
          head: ["", "singular", "plural"],
          rows: [
            ["1st", "אֲנִי — I", "אֲנַחְנוּ — we"],
            ["2nd m.", "אַתָּה — you", "אַתֶּם — you"],
            ["2nd f.", "אַתְּ — you", "אַתֶּן — you"],
            ["3rd m.", "הוּא — he", "הֵם — they"],
            ["3rd f.", "הִיא — she", "הֵן — they"],
          ],
        },
        { type: "tip", body: "There is no word for am, is or are. אֲנִי מוֹרֶה is literally I teacher, and means I am a teacher." },
        {
          type: "examples", items: [
            { he: "שָׁלוֹם, אֲנִי דָּוִד.", en: "Hello, I'm David." },
            { he: "מָה שְׁלוֹמְךָ?", en: "How are you? (to a man)" },
            { he: "מָה שְׁלוֹמֵךְ?", en: "How are you? (to a woman)" },
            { he: "הִיא מוֹרָה.", en: "She is a teacher." },
          ],
        },
      ],
      vocab: [
        { he: "שָׁלוֹם", en: "hello, peace", translit: "shalom" },
        { he: "תּוֹדָה", en: "thank you", translit: "toda" },
        { he: "בְּבַקָּשָׁה", en: "please, you're welcome", translit: "bevakasha" },
        { he: "בֹּקֶר טוֹב", en: "good morning", translit: "boker tov" },
        { he: "לְהִתְרָאוֹת", en: "see you, goodbye", translit: "lehitra'ot" },
        { he: "כֵּן", en: "yes", translit: "ken" },
        { he: "לֹא", en: "no, not", translit: "lo" },
        { he: "מוֹרֶה", en: "teacher (m.)", translit: "more" },
        { he: "מוֹרָה", en: "teacher (f.)", translit: "mora" },
        { he: "סְטוּדֶנְט", en: "student (m.)", translit: "student" },
      ],
      drills: ["vocab", "listen"],
      extra: [
        { type: "choice", q: "You're speaking to one woman. Which is right?", options: ["אַתְּ", "אַתָּה", "אַתֶּן", "הִיא"], correct: 0, why: "אַתְּ is you addressing one woman. אַתָּה is one man, אַתֶּן is several women, הִיא is she." },
        { type: "choice", q: "How do you say “I am a student”?", options: ["אֲנִי סְטוּדֶנְט", "אֲנִי הוּא סְטוּדֶנְט", "אֲנִי יֵשׁ סְטוּדֶנְט", "סְטוּדֶנְט אֲנִי הוּא"], correct: 0, why: "Hebrew has no word for am — the two words sit side by side." },
      ],
    },
    {
      id: "a2",
      title: "Every noun has a gender",
      titleHe: "זָכָר וּנְקֵבָה",
      goal: "Tell masculine nouns from feminine ones, and know the exceptions that matter.",
      sections: [
        { type: "text", body: "Every Hebrew noun is either masculine or feminine, including objects. This isn't decoration: plurals, adjectives and verbs all have to match it, so it's worth learning each noun together with its gender." },
        { type: "text", body: "The usual signal is the ending. Nouns ending in ־ָה or ־ֶת are almost always feminine; nouns with no ending are usually masculine." },
        {
          type: "table", caption: "The usual pattern",
          head: ["masculine", "feminine"],
          rows: [
            ["סֵפֶר — book", "מִטָּה — bed"],
            ["שֻׁלְחָן — table", "מַחְבֶּרֶת — notebook"],
            ["יֶלֶד — boy", "יַלְדָּה — girl"],
            ["כֶּלֶב — dog", "מִשְׁפָּחָה — family"],
          ],
        },
        { type: "tip", body: "A short list of feminine nouns carries no ending at all, and they're all common: עִיר city, אֶרֶץ land, יָד hand, רֶגֶל leg, דֶּרֶךְ way, אֶבֶן stone. Learn these six as exceptions and you'll meet few others." },
      ],
      vocab: [
        { he: "יֶלֶד", en: "boy", translit: "yeled", g: "m" },
        { he: "יַלְדָּה", en: "girl", translit: "yalda", g: "f" },
        { he: "בַּיִת", en: "house", translit: "bayit", g: "m" },
        { he: "מִשְׁפָּחָה", en: "family", translit: "mishpacha", g: "f" },
        { he: "עִיר", en: "city", translit: "ir", g: "f" },
        { he: "אֶרֶץ", en: "land, country", translit: "erets", g: "f" },
        { he: "שֻׁלְחָן", en: "table", translit: "shulchan", g: "m" },
        { he: "מַחְבֶּרֶת", en: "notebook", translit: "machberet", g: "f" },
        { he: "חַלּוֹן", en: "window", translit: "chalon", g: "m" },
        { he: "דֶּלֶת", en: "door", translit: "delet", g: "f" },
      ],
      drills: ["vocab", "gender"],
    },
    {
      id: "a3",
      title: "One and many",
      titleHe: "יָחִיד וְרַבִּים",
      goal: "Form plurals, and recognise the irregular ones you'll use daily.",
      sections: [
        { type: "text", body: "Masculine nouns take ־ִים, feminine nouns take ־וֹת. The vowels inside the word usually shorten when the ending is added." },
        {
          type: "table", caption: "Regular plurals",
          head: ["singular", "plural"],
          rows: [
            ["סֵפֶר — book", "סְפָרִים"],
            ["יֶלֶד — boy", "יְלָדִים"],
            ["מוֹרָה — teacher (f.)", "מוֹרוֹת"],
            ["מִשְׁפָּחָה — family", "מִשְׁפָּחוֹת"],
          ],
        },
        { type: "tip", body: "The ending does not always match the gender. שֻׁלְחָן is masculine but pluralises שֻׁלְחָנוֹת; שָׁנָה is feminine but goes שָׁנִים. The gender doesn't change — only the ending is irregular." },
        {
          type: "table", caption: "The irregulars worth memorising",
          head: ["singular", "plural"],
          rows: [
            ["אִישׁ — man", "אֲנָשִׁים"],
            ["אִשָּׁה — woman", "נָשִׁים"],
            ["בַּיִת — house", "בָּתִּים"],
            ["בֵּן — son", "בָּנִים"],
            ["בַּת — daughter", "בָּנוֹת"],
            ["שָׁנָה — year", "שָׁנִים"],
          ],
        },
      ],
      vocab: [
        { he: "אִישׁ", en: "man", translit: "ish" },
        { he: "אִשָּׁה", en: "woman", translit: "isha" },
        { he: "אֲנָשִׁים", en: "people, men", translit: "anashim" },
        { he: "נָשִׁים", en: "women", translit: "nashim" },
        { he: "בָּתִּים", en: "houses", translit: "batim" },
        { he: "סְפָרִים", en: "books", translit: "sfarim" },
        { he: "יְלָדִים", en: "children", translit: "yeladim" },
        { he: "שָׁנָה", en: "year", translit: "shana" },
      ],
      drills: ["vocab", "plural"],
      extra: [
        { type: "choice", q: "What's the plural of אִשָּׁה?", options: ["נָשִׁים", "אִשּׁוֹת", "אֲנָשִׁים", "אִשִּׁים"], correct: 0, why: "אִשָּׁה → נָשִׁים is irregular; אֲנָשִׁים is the plural of אִישׁ, man." },
      ],
    },
    {
      id: "a4",
      title: "The",
      titleHe: "יְדִיעָה",
      goal: "Use הַ, and know why it sometimes becomes הָ.",
      sections: [
        { type: "text", body: "There is no word for a. סֵפֶר on its own means a book. To say the book you attach הַ to the front — it is part of the word, not a separate one." },
        {
          type: "examples", items: [
            { he: "סֵפֶר → הַסֵּפֶר", en: "a book → the book" },
            { he: "יֶלֶד → הַיֶּלֶד", en: "a boy → the boy" },
            { he: "בַּיִת → הַבַּיִת", en: "a house → the house" },
          ],
        },
        { type: "tip", body: "Before א ה ח ע ר, the הַ lengthens to הָ, because those letters can't take the doubling dot that normally follows: הָאִישׁ the man, הָעִיר the city, הָרֹאשׁ the head." },
      ],
      vocab: [
        { he: "הַסֵּפֶר", en: "the book", translit: "hasefer" },
        { he: "הָאִישׁ", en: "the man", translit: "ha'ish" },
        { he: "הָעִיר", en: "the city", translit: "ha'ir" },
        { he: "הַיּוֹם", en: "today, the day", translit: "hayom" },
        { he: "הַכֹּל", en: "everything", translit: "hakol" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "Which is “the country”?", options: ["הָאָרֶץ", "הַאָרֶץ", "אָרֶץ הַ", "הָאֶרֶץ הַ"], correct: 0, why: "אֶרֶץ starts with א, so the article is הָ — and the noun's own vowel shifts: הָאָרֶץ." },
        { type: "choice", q: "Why is it הָעִיר and not הַעִיר?", options: ["ע can't take the doubling dot, so the vowel lengthens", "עִיר is feminine", "It's an exception with no reason", "Because the word is plural"], correct: 0 },
      ],
    },
    {
      id: "a5",
      title: "Adjectives agree",
      titleHe: "שֵׁם תֹּאַר",
      goal: "Put an adjective after its noun and match it in gender, number and definiteness.",
      sections: [
        { type: "text", body: "An adjective comes after the noun it describes, not before, and it copies three things from it: gender, number, and whether it has the article." },
        {
          type: "table", caption: "גָּדוֹל — big",
          head: ["", "singular", "plural"],
          rows: [
            ["masculine", "יֶלֶד גָּדוֹל", "יְלָדִים גְּדוֹלִים"],
            ["feminine", "יַלְדָּה גְּדוֹלָה", "יְלָדוֹת גְּדוֹלוֹת"],
          ],
        },
        { type: "tip", body: "If the noun takes the article, so does the adjective: הַיֶּלֶד הַגָּדוֹל, the big boy. Leave the second הַ off and you've written a whole sentence instead — הַיֶּלֶד גָּדוֹל means the boy is big." },
      ],
      vocab: [
        { he: "גָּדוֹל", en: "big", translit: "gadol" },
        { he: "קָטָן", en: "small", translit: "katan" },
        { he: "טוֹב", en: "good", translit: "tov" },
        { he: "רַע", en: "bad", translit: "ra" },
        { he: "יָפֶה", en: "beautiful", translit: "yafe" },
        { he: "חָדָשׁ", en: "new", translit: "chadash" },
        { he: "יָשָׁן", en: "old (of things)", translit: "yashan" },
        { he: "קָשֶׁה", en: "hard, difficult", translit: "kashe" },
      ],
      drills: ["vocab", "agree"],
      extra: [
        { type: "choice", q: "“The big house” is —", options: ["הַבַּיִת הַגָּדוֹל", "הַבַּיִת גָּדוֹל", "בַּיִת הַגָּדוֹל", "הַגָּדוֹל הַבַּיִת"], correct: 0, why: "Both words take the article. Without the second one, הַבַּיִת גָּדוֹל, you've said the house is big." },
        { type: "choice", q: "What does הַיַּלְדָּה קְטַנָּה mean?", options: ["The girl is small", "The small girl", "A small girl", "The girl and the small one"], correct: 0, why: "The adjective has no article, so this is a sentence, not a phrase." },
      ],
    },
    {
      id: "a6",
      title: "There is, there isn't",
      titleHe: "יֵשׁ וְאֵין",
      goal: "Say what exists and what doesn't.",
      sections: [
        { type: "text", body: "יֵשׁ means there is or there are — one word for both, since it doesn't change for number. Its opposite is אֵין." },
        {
          type: "examples", items: [
            { he: "יֵשׁ סֵפֶר עַל הַשֻּׁלְחָן.", en: "There is a book on the table." },
            { he: "יֵשׁ אֲנָשִׁים בַּבַּיִת.", en: "There are people in the house." },
            { he: "אֵין קָפֶה.", en: "There's no coffee." },
            { he: "אֵין מַיִם בַּבַּקְבּוּק.", en: "There's no water in the bottle." },
          ],
        },
        { type: "tip", body: "אֵין also does the work of isn't in a nominal sentence: הוּא אֵינוֹ מוֹרֶה, he is not a teacher — though in speech people simply say הוּא לֹא מוֹרֶה." },
      ],
      vocab: [
        { he: "יֵשׁ", en: "there is, there are", translit: "yesh" },
        { he: "אֵין", en: "there isn't", translit: "ein" },
        { he: "עַל", en: "on", translit: "al" },
        { he: "כָּאן", en: "here", translit: "kan" },
        { he: "שָׁם", en: "there", translit: "sham" },
        { he: "הַרְבֵּה", en: "a lot, many", translit: "harbe" },
        { he: "קְצָת", en: "a little", translit: "ktsat" },
      ],
      drills: ["vocab", "listen"],
    },
    {
      id: "a7",
      title: "In, to, from",
      titleHe: "מִלּוֹת יַחַס",
      goal: "Attach בְּ, לְ and מִ, and combine them with the article.",
      sections: [
        { type: "text", body: "Three of the commonest prepositions are single letters glued to the front of the word: בְּ in or at, לְ to, מִ from." },
        {
          type: "examples", items: [
            { he: "בְּבַיִת", en: "in a house" },
            { he: "לְעִיר", en: "to a city" },
            { he: "מִסֵּפֶר", en: "from a book" },
          ],
        },
        { type: "text", body: "When the word is definite, the הַ doesn't survive alongside them — it merges into the preposition's vowel." },
        {
          type: "table", caption: "With the article",
          head: ["indefinite", "definite"],
          rows: [
            ["בְּבַיִת — in a house", "בַּבַּיִת — in the house"],
            ["לְעִיר — to a city", "לָעִיר — to the city"],
            ["מִבַּיִת — from a house", "מֵהַבַּיִת — from the house"],
          ],
        },
        { type: "tip", body: "מִ is the exception: it keeps the הַ visible and lengthens its own vowel instead — מֵהַבַּיִת, not מַבַּיִת." },
      ],
      vocab: [
        { he: "בְּ", en: "in, at", translit: "be-" },
        { he: "לְ", en: "to, for", translit: "le-" },
        { he: "מִ", en: "from", translit: "mi-" },
        { he: "עִם", en: "with", translit: "im" },
        { he: "אֶל", en: "to, towards", translit: "el" },
        { he: "בֵּין", en: "between", translit: "bein" },
        { he: "לְיַד", en: "next to", translit: "leyad" },
        { he: "תַּחַת", en: "under", translit: "tachat" },
      ],
      drills: ["vocab"],
      extra: [
        { type: "choice", q: "“In the city” is —", options: ["בָּעִיר", "בְּהָעִיר", "בַּעִיר", "בְּעִיר"], correct: 0, why: "The article merges into the preposition; because עִיר starts with ע the vowel is kamatz, giving בָּעִיר. בְּעִיר without it means in a city." },
      ],
    },
    {
      id: "a8",
      title: "Asking",
      titleHe: "שְׁאֵלוֹת",
      goal: "Ask what, who, where, when, why and how much.",
      sections: [
        { type: "text", body: "Question words go first, and nothing else in the sentence moves — Hebrew doesn't invert word order to ask." },
        {
          type: "examples", items: [
            { he: "מָה זֶה?", en: "What is this?" },
            { he: "מִי הָאִישׁ?", en: "Who is the man?" },
            { he: "אֵיפֹה הַסֵּפֶר?", en: "Where is the book?" },
            { he: "מָתַי אַתָּה בָּא?", en: "When are you coming?" },
            { he: "לָמָּה לֹא?", en: "Why not?" },
            { he: "כַּמָּה זֶה עוֹלֶה?", en: "How much does it cost?" },
          ],
        },
        { type: "tip", body: "A yes-or-no question is just the statement with a rising tone. הַאִם can be put at the front in writing, but speech rarely bothers." },
      ],
      vocab: [
        { he: "מָה", en: "what", translit: "ma" },
        { he: "מִי", en: "who", translit: "mi" },
        { he: "אֵיפֹה", en: "where", translit: "eifo" },
        { he: "מָתַי", en: "when", translit: "matai" },
        { he: "לָמָּה", en: "why", translit: "lama" },
        { he: "אֵיךְ", en: "how", translit: "eich" },
        { he: "כַּמָּה", en: "how much, how many", translit: "kama" },
        { he: "אֵיזֶה", en: "which", translit: "eize" },
      ],
      drills: ["vocab", "listen"],
    },
    {
      id: "a9",
      title: "What's happening now",
      titleHe: "זְמַן הֹוֶה",
      goal: "Use the present tense — four forms, no persons.",
      sections: [
        { type: "text", body: "The Hebrew present has only four forms, and they change for gender and number rather than for person. אֲנִי כּוֹתֵב, אַתָּה כּוֹתֵב and הוּא כּוֹתֵב are all the same word — the pronoun does the rest." },
        { type: "binyan", id: "paal", tense: "present" },
        { type: "text", body: "It covers both English presents at once: אֲנִי קוֹרֵא is I read and I am reading." },
        {
          type: "examples", items: [
            { he: "אֲנִי לוֹמֵד עִבְרִית.", en: "I'm learning Hebrew." },
            { he: "הִיא גָּרָה בָּעִיר.", en: "She lives in the city." },
            { he: "הֵם אוֹכְלִים בַּבַּיִת.", en: "They're eating at home." },
          ],
        },
      ],
      vocab: [
        { he: "לוֹמֵד", en: "learns, studies", translit: "lomed" },
        { he: "כּוֹתֵב", en: "writes", translit: "kotev" },
        { he: "קוֹרֵא", en: "reads", translit: "kore" },
        { he: "אוֹכֵל", en: "eats", translit: "ochel" },
        { he: "הוֹלֵךְ", en: "goes, walks", translit: "holech" },
        { he: "יוֹשֵׁב", en: "sits", translit: "yoshev" },
        { he: "גָּר", en: "lives, resides", translit: "gar" },
        { he: "רוֹצֶה", en: "wants", translit: "rotse" },
        { he: "אוֹהֵב", en: "loves, likes", translit: "ohev" },
        { he: "עִבְרִית", en: "Hebrew", translit: "ivrit" },
      ],
      drills: ["vocab", "conjugate:paal:present", "build"],
    },
    {
      id: "a10",
      title: "Counting",
      titleHe: "מִסְפָּרִים",
      goal: "Count to ten — and pick the right set of numbers.",
      sections: [
        { type: "text", body: "Hebrew numbers have two sets, and the one you use depends on the gender of what you're counting. This catches every learner: the form that looks feminine, ending in ־ָה, is the one used with masculine nouns." },
        {
          type: "table", caption: "One to ten",
          head: ["", "with feminine nouns", "with masculine nouns"],
          rows: [
            ["1", "אַחַת", "אֶחָד"],
            ["2", "שְׁתַּיִם", "שְׁנַיִם"],
            ["3", "שָׁלוֹשׁ", "שְׁלוֹשָׁה"],
            ["4", "אַרְבַּע", "אַרְבָּעָה"],
            ["5", "חָמֵשׁ", "חֲמִשָּׁה"],
            ["6", "שֵׁשׁ", "שִׁשָּׁה"],
            ["7", "שֶׁבַע", "שִׁבְעָה"],
            ["8", "שְׁמוֹנֶה", "שְׁמוֹנָה"],
            ["9", "תֵּשַׁע", "תִּשְׁעָה"],
            ["10", "עֶשֶׂר", "עֲשָׂרָה"],
          ],
        },
        { type: "tip", body: "Counting out loud — one, two, three with nothing being counted — uses the feminine set. So does giving a phone number." },
        { type: "tip", body: "One is the exception to the exception: it follows its noun like an adjective. סֵפֶר אֶחָד, one book. Every other number comes first: שְׁלוֹשָׁה סְפָרִים." },
      ],
      vocab: [
        { he: "אֶחָד", en: "one (m.)", translit: "echad" },
        { he: "שְׁנַיִם", en: "two (m.)", translit: "shnayim" },
        { he: "שְׁלוֹשָׁה", en: "three (m.)", translit: "shlosha" },
        { he: "אַרְבָּעָה", en: "four (m.)", translit: "arba'a" },
        { he: "חֲמִשָּׁה", en: "five (m.)", translit: "chamisha" },
        { he: "עֲשָׂרָה", en: "ten (m.)", translit: "asara" },
        { he: "מִסְפָּר", en: "number", translit: "mispar" },
      ],
      drills: ["vocab", "listen"],
      extra: [
        { type: "choice", q: "“Three books” (סְפָרִים is masculine) —", options: ["שְׁלוֹשָׁה סְפָרִים", "שָׁלוֹשׁ סְפָרִים", "סְפָרִים שְׁלוֹשָׁה", "שָׁלוֹשׁ הַסְּפָרִים"], correct: 0, why: "Masculine nouns take the ־ָה set, and the number comes first." },
        { type: "choice", q: "You're counting aloud: one, two, three. Which set?", options: ["The feminine set", "The masculine set", "Either", "Neither — there's a third"], correct: 0 },
      ],
    },
  ],
};
