/* Themed vocabulary — verbs, abstractions, and the literary register.

   The concrete packs get you through a day. These get you through a page:
   the verbs that carry most sentences, the abstract nouns literary prose is
   built from, and the specifically old vocabulary — priests, covenants,
   inheritances — that the public-domain library assumes you have. */

export const PACKS_2 = [
  {
    id: "vday", level: 4, after: "v2",
    title: "A day, in verbs",
    titleHe: "פְּעָלִים שֶׁל יוֹם",
    goal: "Say what you did from waking to sleeping.",
    note: "Listed in the present, which is the form you'll recognise. Each one is a participle: it names the action and the person doing it at once.",
    words: [
      { he: "מִתְעוֹרֵר", en: "wakes up", translit: "mit'orer" },
      { he: "קָם", en: "gets up", translit: "kam" },
      { he: "מִתְרַחֵץ", en: "washes, bathes", translit: "mitrachets" },
      { he: "מִסְתָּרֵק", en: "combs their hair", translit: "mistarek" },
      { he: "יוֹצֵא", en: "goes out, exits", translit: "yotse" },
      { he: "חוֹזֵר", en: "returns", translit: "chozer" },
      { he: "רָץ", en: "runs", translit: "rats" },
      { he: "עוֹלֶה", en: "goes up, costs", translit: "ole" },
      { he: "יוֹרֵד", en: "goes down", translit: "yored" },
      { he: "עוֹמֵד", en: "stands", translit: "omed" },
      { he: "שׁוֹכֵב", en: "lies down", translit: "shochev" },
      { he: "יָשֵׁן", en: "sleeps", translit: "yashen" },
      { he: "פּוֹתֵחַ", en: "opens", translit: "pote'ach" },
      { he: "סוֹגֵר", en: "closes", translit: "soger" },
      { he: "לוֹקֵחַ", en: "takes", translit: "loke'ach" },
      { he: "נוֹתֵן", en: "gives", translit: "noten" },
      { he: "שָׂם", en: "puts", translit: "sam" },
      { he: "מֵבִיא", en: "brings", translit: "mevi" },
      { he: "מוֹצֵא", en: "finds", translit: "motse" },
      { he: "מְחַפֵּשׂ", en: "searches for", translit: "mechapes" },
      { he: "עוֹזֵר", en: "helps", translit: "ozer" },
      { he: "נָח", en: "rests", translit: "nach" },
      { he: "מְחַכֶּה", en: "waits", translit: "mechake" },
      { he: "מַתְחִיל", en: "begins", translit: "matchil" },
      { he: "גּוֹמֵר", en: "finishes", translit: "gomer" },
      { he: "מְנַסֶּה", en: "tries", translit: "menase" },
      { he: "שׁוֹלֵחַ", en: "sends", translit: "shole'ach" },
      { he: "מְקַבֵּל", en: "receives", translit: "mekabel" },
      { he: "עוֹנֶה", en: "answers", translit: "one" },
      { he: "שׁוֹאֵל", en: "asks", translit: "sho'el" },
    ],
  },
  {
    id: "vmind", level: 4, after: "v5",
    title: "Speech and thought",
    titleHe: "אֲמִירָה וּמַחֲשָׁבָה",
    goal: "The verbs that introduce everything else in a sentence.",
    note: "These are the verbs that take שֶׁ after them — I think that…, he said that…. They're how clauses get joined, which is why they matter more than their frequency suggests.",
    words: [
      { he: "אוֹמֵר", en: "says", translit: "omer" },
      { he: "חוֹשֵׁב", en: "thinks", translit: "choshev" },
      { he: "מֵבִין", en: "understands", translit: "mevin" },
      { he: "זוֹכֵר", en: "remembers", translit: "zocher" },
      { he: "שׁוֹכֵחַ", en: "forgets", translit: "shoke'ach" },
      { he: "מַאֲמִין", en: "believes", translit: "ma'amin" },
      { he: "מְקַוֶּה", en: "hopes", translit: "mekave" },
      { he: "מַרְגִּישׁ", en: "feels", translit: "margish" },
      { he: "שׂוֹנֵא", en: "hates", translit: "sone" },
      { he: "מַסְכִּים", en: "agrees", translit: "maskim" },
      { he: "מִתְנַגֵּד", en: "opposes", translit: "mitnaged" },
      { he: "מַחְלִיט", en: "decides", translit: "machlit" },
      { he: "מְבַקֵּשׁ", en: "requests", translit: "mevakesh" },
      { he: "מוֹדֶה", en: "thanks, admits", translit: "mode" },
      { he: "מַבְטִיחַ", en: "promises", translit: "mavtiach" },
      { he: "מְסַפֵּר", en: "tells, recounts", translit: "mesaper" },
      { he: "צוֹעֵק", en: "shouts", translit: "tso'ek" },
      { he: "לוֹחֵשׁ", en: "whispers", translit: "lochesh" },
      { he: "שׁוֹתֵק", en: "is silent", translit: "shotek" },
      { he: "מַכְחִישׁ", en: "denies", translit: "machchish" },
      { he: "מְתָאֵר", en: "describes", translit: "meta'er" },
      { he: "מַזְכִּיר", en: "mentions, reminds", translit: "mazkir" },
      { he: "מְגַלֶּה", en: "discovers, reveals", translit: "megale" },
      { he: "מַסְתִּיר", en: "hides", translit: "mastir" },
    ],
  },
  {
    id: "vfeel", level: 5, after: "s2",
    title: "Feeling and character",
    titleHe: "רְגָשׁוֹת וְאֹפִי",
    goal: "Describe a person, and how they are.",
    note: "Most of these come in pairs: an adjective for the state and an abstract noun for the thing itself — שָׂמֵחַ happy, שִׂמְחָה joy.",
    words: [
      { he: "רֶגֶשׁ", en: "feeling, emotion", translit: "regesh" },
      { he: "עָצוּב", en: "sad", translit: "atsuv" },
      { he: "כּוֹעֵס", en: "angry", translit: "ko'es" },
      { he: "מְפַחֵד", en: "afraid", translit: "mefached" },
      { he: "מֻפְתָּע", en: "surprised", translit: "mufta" },
      { he: "עָיֵף", en: "tired", translit: "ayef" },
      { he: "רָעֵב", en: "hungry", translit: "ra'ev" },
      { he: "צָמֵא", en: "thirsty", translit: "tsame" },
      { he: "מְרֻצֶּה", en: "pleased", translit: "merutse" },
      { he: "מְאֻכְזָב", en: "disappointed", translit: "me'uchzav" },
      { he: "גֵּאֶה", en: "proud", translit: "ge'e" },
      { he: "בַּיְשָׁן", en: "shy", translit: "bayshan" },
      { he: "אַמִּיץ", en: "brave", translit: "amits" },
      { he: "חָכָם", en: "wise, clever", translit: "chacham" },
      { he: "טִפֵּשׁ", en: "foolish", translit: "tipesh" },
      { he: "נֶחְמָד", en: "nice", translit: "nechmad" },
      { he: "אָדִיב", en: "polite, courteous", translit: "adiv" },
      { he: "נָדִיב", en: "generous", translit: "nadiv" },
      { he: "אַכְזָר", en: "cruel", translit: "achzar" },
      { he: "סַבְלָנוּת", en: "patience", translit: "savlanut" },
      { he: "אַהֲבָה", en: "love", translit: "ahava" },
      { he: "שִׂנְאָה", en: "hatred", translit: "sin'a" },
      { he: "פַּחַד", en: "fear", translit: "pachad" },
      { he: "שִׂמְחָה", en: "joy", translit: "simcha" },
      { he: "עֶצֶב", en: "sadness", translit: "etsev" },
      { he: "כַּעַס", en: "anger", translit: "ka'as" },
      { he: "תִּקְוָה", en: "hope", translit: "tikva" },
      { he: "בּוּשָׁה", en: "shame", translit: "busha" },
      { he: "גַּעְגּוּעִים", en: "longing", translit: "ga'agu'im" },
    ],
  },
  {
    id: "vabstract", level: 5, after: "s3",
    title: "Ideas and abstractions",
    titleHe: "מֻשָּׂגִים",
    goal: "The nouns essays and novels are actually built from.",
    note: "This is the vocabulary that separates a page you can follow from one you can't. Almost none of it appears in a beginner's conversation and all of it appears in a book.",
    words: [
      { he: "עוֹלָם", en: "world", translit: "olam" },
      { he: "חַיִּים", en: "life", translit: "chayim" },
      { he: "מָוֶת", en: "death", translit: "mavet" },
      { he: "מָקוֹם", en: "place", translit: "makom" },
      { he: "אֱמֶת", en: "truth", translit: "emet" },
      { he: "שֶׁקֶר", en: "lie, falsehood", translit: "sheker" },
      { he: "צֶדֶק", en: "justice", translit: "tsedek" },
      { he: "חֹפֶשׁ", en: "freedom", translit: "chofesh" },
      { he: "כֹּחַ", en: "strength, power", translit: "ko'ach" },
      { he: "חָכְמָה", en: "wisdom", translit: "chochma" },
      { he: "דַּעַת", en: "knowledge", translit: "da'at" },
      { he: "בִּינָה", en: "understanding", translit: "bina" },
      { he: "נְשָׁמָה", en: "soul", translit: "neshama" },
      { he: "גּוֹרָל", en: "fate", translit: "goral" },
      { he: "מַזָּל", en: "luck, fortune", translit: "mazal" },
      { he: "סוֹד", en: "secret", translit: "sod" },
      { he: "זִכָּרוֹן", en: "memory", translit: "zikaron" },
      { he: "חֲלוֹם", en: "dream", translit: "chalom" },
      { he: "מְצִיאוּת", en: "reality", translit: "metsi'ut" },
      { he: "מַחֲשָׁבָה", en: "thought", translit: "machshava" },
      { he: "רַעְיוֹן", en: "idea", translit: "ra'ayon" },
      { he: "סִבָּה", en: "reason, cause", translit: "siba" },
      { he: "תּוֹצָאָה", en: "result", translit: "totsa'a" },
      { he: "מַטָּרָה", en: "purpose, goal", translit: "matara" },
      { he: "עֵרֶךְ", en: "value, worth", translit: "erech" },
      { he: "טֶבַע", en: "nature", translit: "teva" },
      { he: "עַם", en: "people, nation", translit: "am" },
      { he: "מְדִינָה", en: "state, country", translit: "medina" },
      { he: "מִלְחָמָה", en: "war", translit: "milchama" },
      { he: "דּוֹר", en: "generation", translit: "dor" },
      { he: "כָּבוֹד", en: "honour, glory", translit: "kavod" },
      { he: "צוּרָה", en: "form, shape", translit: "tsura" },
      { he: "עִנְיָן", en: "matter, interest", translit: "inyan" },
      { he: "יְכֹלֶת", en: "ability", translit: "yecholet" },
    ],
  },
  {
    id: "vlit", level: 6, after: "l2",
    title: "The literary register",
    titleHe: "לְשׁוֹן סִפְרוּת",
    goal: "The words a hundred-year-old page assumes you know.",
    note: "Every one of these is common in the library and rare in conversation. They are the reason a page can look impossible when you know two thousand modern words.",
    words: [
      { he: "אָדוֹן", en: "lord, master, sir", translit: "adon" },
      { he: "עֶבֶד", en: "servant, slave", translit: "eved" },
      { he: "מֶלֶךְ", en: "king", translit: "melech" },
      { he: "נָבִיא", en: "prophet", translit: "navi" },
      { he: "כֹּהֵן", en: "priest", translit: "kohen" },
      { he: "בְּרִית", en: "covenant", translit: "brit" },
      { he: "מִצְוָה", en: "commandment, good deed", translit: "mitsva" },
      { he: "חֹק", en: "statute, law", translit: "chok" },
      { he: "חֶסֶד", en: "kindness, grace", translit: "chesed" },
      { he: "רַחֲמִים", en: "mercy", translit: "rachamim" },
      { he: "קֹדֶשׁ", en: "holiness", translit: "kodesh" },
      { he: "טָהוֹר", en: "pure", translit: "tahor" },
      { he: "קָרְבָּן", en: "sacrifice, victim", translit: "korban" },
      { he: "נַחֲלָה", en: "inheritance, estate", translit: "nachala" },
      { he: "זֶרַע", en: "seed, offspring", translit: "zera" },
      { he: "גּוֹי", en: "nation, gentile", translit: "goy" },
      { he: "חָזוֹן", en: "vision", translit: "chazon" },
      { he: "מוּסָר", en: "morals, rebuke", translit: "musar" },
      { he: "יִרְאָה", en: "awe, fear", translit: "yir'a" },
      { he: "תְּפִלָּה", en: "prayer", translit: "tfila" },
      { he: "צָרָה", en: "trouble, distress", translit: "tsara" },
      { he: "יְשׁוּעָה", en: "salvation", translit: "yeshu'a" },
      { he: "אָבַד", en: "was lost, perished", translit: "avad" },
      { he: "הִנֵּה", en: "behold, here is", translit: "hine" },
      { he: "אוּלָם", en: "however, but", translit: "ulam" },
      { he: "אַךְ", en: "only, yet", translit: "ach" },
      { he: "בִּלְתִּי", en: "un-, without", translit: "bilti" },
      { he: "מְאֹד", en: "very, exceedingly", translit: "me'od" },
      { he: "יַחַד", en: "together", translit: "yachad" },
      { he: "לְבַד", en: "alone", translit: "levad" },
    ],
  },
  {
    id: "vpoetry", level: 6, after: "l4",
    title: "The vocabulary of verse",
    titleHe: "לְשׁוֹן הַשִּׁיר",
    goal: "The words poems reach for, and their plainer twins.",
    note: "Hebrew poetry has a parallel vocabulary: for almost every ordinary word there is a higher one, and verse alternates between them. Knowing the pairs is half of reading a poem.",
    words: [
      { he: "לֵבָב", en: "heart (poetic)", translit: "levav" },
      { he: "נֶפֶשׁ", en: "soul, self, person", translit: "nefesh" },
      { he: "אוֹר", en: "light", translit: "or" },
      { he: "חֹשֶׁךְ", en: "darkness", translit: "choshech" },
      { he: "שַׁחַר", en: "dawn", translit: "shachar" },
      { he: "דִּמְעָה", en: "tear", translit: "dim'a" },
      { he: "שִׁיר", en: "song, poem", translit: "shir" },
      { he: "קוֹל", en: "voice, sound", translit: "kol" },
      { he: "דְּמָמָה", en: "silence, stillness", translit: "dmama" },
      { he: "עָפָר", en: "dust", translit: "afar" },
      { he: "סֶלַע", en: "rock", translit: "sela" },
      { he: "גַּל", en: "wave", translit: "gal" },
      { he: "כּוֹכָבִים", en: "stars", translit: "kochavim" },
      { he: "רָקִיעַ", en: "firmament, sky", translit: "raki'a" },
      { he: "תְּהוֹם", en: "abyss, deep", translit: "tehom" },
      { he: "צֵל", en: "shadow", translit: "tsel" },
      { he: "לַהַב", en: "flame, blade", translit: "lahav" },
      { he: "כְּנַף", en: "wing (construct)", translit: "knaf" },
      { he: "מַעֲשֶׂה", en: "deed, work", translit: "ma'ase" },
      { he: "פְּרִי", en: "fruit", translit: "pri" },
      { he: "שֹׁרֶשׁ", en: "root", translit: "shoresh" },
      { he: "נִצָּן", en: "bud", translit: "nitsan" },
      { he: "אֵבֶל", en: "mourning", translit: "evel" },
      { he: "גִּיל", en: "rejoicing", translit: "gil" },
      { he: "כְּאֵב", en: "pain", translit: "ke'ev" },
      { he: "עֹז", en: "might", translit: "oz" },
    ],
  },
];
