/* Themed vocabulary — the connective tissue.

   The first two files cover things you can point at and things you can do.
   These cover the rest: the numbers past ten, the calendar, the adjectives
   that describe anything, the small words that hold sentences together, and
   the register of argument — which is what an essay is made of. */

export const PACKS_3 = [
  {
    id: "vnum", level: 2, after: "a10",
    title: "Numbers past ten",
    titleHe: "מִסְפָּרִים",
    goal: "Count to a thousand, and put things in order.",
    note: "Eleven to nineteen are built by putting the unit before עֶשְׂרֵה (feminine) or עָשָׂר (masculine). The tens have one form for both genders, which is a relief after the first ten.",
    words: [
      { he: "אַחַת עֶשְׂרֵה", en: "eleven (f.)", translit: "achat esre" },
      { he: "שְׁתֵּים עֶשְׂרֵה", en: "twelve (f.)", translit: "shteim esre" },
      { he: "אַחַד עָשָׂר", en: "eleven (m.)", translit: "achad asar" },
      { he: "שְׁנֵים עָשָׂר", en: "twelve (m.)", translit: "shneim asar" },
      { he: "עֶשְׂרִים", en: "twenty", translit: "esrim" },
      { he: "שְׁלוֹשִׁים", en: "thirty", translit: "shloshim" },
      { he: "אַרְבָּעִים", en: "forty", translit: "arba'im" },
      { he: "חֲמִשִּׁים", en: "fifty", translit: "chamishim" },
      { he: "שִׁשִּׁים", en: "sixty", translit: "shishim" },
      { he: "שִׁבְעִים", en: "seventy", translit: "shiv'im" },
      { he: "שְׁמוֹנִים", en: "eighty", translit: "shmonim" },
      { he: "תִּשְׁעִים", en: "ninety", translit: "tish'im" },
      { he: "מֵאָה", en: "hundred", translit: "me'a" },
      { he: "מָאתַיִם", en: "two hundred", translit: "matayim" },
      { he: "אֶלֶף", en: "thousand", translit: "elef" },
      { he: "רִאשׁוֹן", en: "first", translit: "rishon" },
      { he: "שֵׁנִי", en: "second", translit: "sheni" },
      { he: "שְׁלִישִׁי", en: "third", translit: "shlishi" },
      { he: "רְבִיעִי", en: "fourth", translit: "revi'i" },
      { he: "חֲמִישִׁי", en: "fifth", translit: "chamishi" },
      { he: "אַחֲרוֹן", en: "last", translit: "acharon" },
      { he: "חֵצִי", en: "half", translit: "chetsi" },
      { he: "רֶבַע", en: "quarter", translit: "reva" },
      { he: "זוּג", en: "pair, couple", translit: "zug" },
      { he: "פַּעַם", en: "once, a time", translit: "pa'am" },
      { he: "פַּעֲמַיִם", en: "twice", translit: "pa'amayim" },
    ],
  },
  {
    id: "vadj", level: 2, after: "a6",
    title: "Describing things",
    titleHe: "שְׁמוֹת תֹּאַר",
    goal: "Forty adjectives, mostly in opposite pairs.",
    note: "Learning adjectives in pairs halves the work and doubles what you can say — and Hebrew obliges by pairing most of them neatly.",
    words: [
      { he: "אָרֹךְ", en: "long", translit: "aroch" },
      { he: "קָצָר", en: "short", translit: "katsar" },
      { he: "גָּבוֹהַּ", en: "tall, high", translit: "gavoha" },
      { he: "נָמוּךְ", en: "low, short", translit: "namuch" },
      { he: "רָחָב", en: "wide", translit: "rachav" },
      { he: "צַר", en: "narrow", translit: "tsar" },
      { he: "כָּבֵד", en: "heavy", translit: "kaved" },
      { he: "קַל", en: "light, easy", translit: "kal" },
      { he: "מָלֵא", en: "full", translit: "male" },
      { he: "רֵיק", en: "empty", translit: "reik" },
      { he: "חָזָק", en: "strong", translit: "chazak" },
      { he: "חַלָּשׁ", en: "weak", translit: "chalash" },
      { he: "נָקִי", en: "clean", translit: "naki" },
      { he: "מְלֻכְלָךְ", en: "dirty", translit: "meluchlach" },
      { he: "מָהִיר", en: "fast", translit: "mahir" },
      { he: "אִטִּי", en: "slow", translit: "iti" },
      { he: "רַךְ", en: "soft", translit: "rach" },
      { he: "קָשֶׁה", en: "hard, difficult", translit: "kashe" },
      { he: "עָשִׁיר", en: "rich", translit: "ashir" },
      { he: "עָנִי", en: "poor", translit: "ani" },
      { he: "צָעִיר", en: "young", translit: "tsa'ir" },
      { he: "מְבֻגָּר", en: "grown up", translit: "mevugar" },
      { he: "חָשׁוּב", en: "important", translit: "chashuv" },
      { he: "מְעַנְיֵן", en: "interesting", translit: "me'anyen" },
      { he: "מְשַׁעֲמֵם", en: "boring", translit: "mesha'amem" },
      { he: "מוּזָר", en: "strange", translit: "muzar" },
      { he: "רָגִיל", en: "ordinary, used to", translit: "ragil" },
      { he: "אֲמִתִּי", en: "real, true", translit: "amiti" },
      { he: "שָׁלֵם", en: "whole, complete", translit: "shalem" },
      { he: "שָׁקֵט", en: "quiet", translit: "shaket" },
      { he: "רוֹעֵשׁ", en: "noisy", translit: "ro'esh" },
      { he: "בָּרוּר", en: "clear", translit: "barur" },
      { he: "מְסֻכָּן", en: "dangerous", translit: "mesukan" },
      { he: "בָּטוּחַ", en: "safe, certain", translit: "batuach" },
    ],
  },
  {
    id: "vtime", level: 3, after: "b6",
    title: "The calendar",
    titleHe: "לוּחַ הַשָּׁנָה",
    goal: "Months, festivals and the words that place an event in time.",
    note: "The Hebrew months are lunar and don't line up with January. They matter here because dates in older books are given in them, with no Gregorian equivalent.",
    words: [
      { he: "תִּשְׁרֵי", en: "Tishrei (Sept–Oct)", translit: "tishrei" },
      { he: "כִּסְלֵו", en: "Kislev (Nov–Dec)", translit: "kislev" },
      { he: "שְׁבָט", en: "Shvat (Jan–Feb)", translit: "shvat" },
      { he: "נִיסָן", en: "Nisan (Mar–Apr)", translit: "nisan" },
      { he: "אִיָּר", en: "Iyar (Apr–May)", translit: "iyar" },
      { he: "אָב", en: "Av (Jul–Aug)", translit: "av" },
      { he: "חַג", en: "festival, holiday", translit: "chag" },
      { he: "שַׁבָּת", en: "Sabbath, Saturday", translit: "shabat" },
      { he: "רֹאשׁ הַשָּׁנָה", en: "New Year", translit: "rosh hashana" },
      { he: "פֶּסַח", en: "Passover", translit: "pesach" },
      { he: "סֻכּוֹת", en: "Sukkot", translit: "sukot" },
      { he: "חֲנֻכָּה", en: "Hanukkah", translit: "chanuka" },
      { he: "תַּאֲרִיךְ", en: "date", translit: "ta'arich" },
      { he: "אֶתְמוֹל", en: "yesterday", translit: "etmol" },
      { he: "הַיּוֹם", en: "today", translit: "hayom" },
      { he: "מָחָר", en: "tomorrow", translit: "machar" },
      { he: "עַכְשָׁו", en: "now", translit: "achshav" },
      { he: "אָז", en: "then", translit: "az" },
      { he: "מִיָּד", en: "immediately", translit: "miyad" },
      { he: "בֵּינְתַיִם", en: "meanwhile", translit: "beintayim" },
      { he: "לִפְנֵי", en: "before", translit: "lifnei" },
      { he: "אַחֲרֵי", en: "after", translit: "acharei" },
      { he: "בְּמֶשֶׁךְ", en: "during, for", translit: "bemeshech" },
      { he: "עַד", en: "until", translit: "ad" },
      { he: "מֵאָז", en: "since then", translit: "me'az" },
      { he: "לְעוֹלָם", en: "forever, ever", translit: "le'olam" },
      { he: "מֻקְדָּם", en: "early", translit: "mukdam" },
      { he: "מְאֻחָר", en: "late", translit: "me'uchar" },
    ],
  },
  {
    id: "vquant", level: 3, after: "b9",
    title: "How much, how many",
    titleHe: "כַּמּוּת וְהַשְׁוָאָה",
    goal: "Quantify things, and compare them.",
    note: "Comparison has one pattern and no exceptions: יוֹתֵר more and פָּחוֹת less, with מִ for than. גָּדוֹל יוֹתֵר מִמֶּנִּי — bigger than me.",
    words: [
      { he: "כֹּל", en: "all, every", translit: "kol" },
      { he: "רֹב", en: "most of", translit: "rov" },
      { he: "מִעוּט", en: "a minority", translit: "mi'ut" },
      { he: "מְעַט", en: "a little, few", translit: "me'at" },
      { he: "מַסְפִּיק", en: "enough", translit: "maspik" },
      { he: "יוֹתֵר", en: "more", translit: "yoter" },
      { he: "פָּחוֹת", en: "less", translit: "pachot" },
      { he: "בְּיוֹתֵר", en: "the most (superlative)", translit: "beyoter" },
      { he: "הֲכִי", en: "the most (spoken)", translit: "hachi" },
      { he: "כְּמוֹ", en: "like, as", translit: "kmo" },
      { he: "אוֹתוֹ דָּבָר", en: "the same thing", translit: "oto davar" },
      { he: "שׁוֹנֶה", en: "different", translit: "shone" },
      { he: "דּוֹמֶה", en: "similar", translit: "dome" },
      { he: "חֵלֶק", en: "part, portion", translit: "chelek" },
      { he: "מִסְפָּר", en: "number", translit: "mispar" },
      { he: "כַּמּוּת", en: "quantity", translit: "kamut" },
      { he: "מִשְׁקָל", en: "weight", translit: "mishkal" },
      { he: "גֹּדֶל", en: "size", translit: "godel" },
      { he: "אֹרֶךְ", en: "length", translit: "orech" },
      { he: "מֶרְחָק", en: "distance", translit: "merchak" },
      { he: "קִילוֹ", en: "kilo", translit: "kilo" },
      { he: "מֶטֶר", en: "metre", translit: "meter" },
      { he: "כִּמְעַט", en: "almost", translit: "kim'at" },
      { he: "בְּעֵרֶךְ", en: "approximately", translit: "be'erech" },
      { he: "לְפָחוֹת", en: "at least", translit: "lefachot" },
      { he: "לְכָל הַיּוֹתֵר", en: "at most", translit: "lechol hayoter" },
    ],
  },
  {
    id: "vconn", level: 5, after: "s1",
    title: "The small words that hold an argument together",
    titleHe: "מִלּוֹת קִשּׁוּר",
    goal: "Connectives — the vocabulary of essays rather than conversation.",
    note: "These carry almost no meaning on their own and decide the shape of everything around them. In non-fiction they're the most frequent words on the page after the articles.",
    words: [
      { he: "לָכֵן", en: "therefore", translit: "lachen" },
      { he: "לְפִיכָךְ", en: "consequently", translit: "lefichach" },
      { he: "אַף עַל פִּי", en: "although", translit: "af al pi" },
      { he: "לַמְרוֹת", en: "despite", translit: "lamrot" },
      { he: "בְּעוֹד", en: "while, whereas", translit: "be'od" },
      { he: "לְעֻמַּת", en: "as opposed to", translit: "le'umat" },
      { he: "כְּלוֹמַר", en: "that is to say", translit: "klomar" },
      { he: "כְּגוֹן", en: "such as", translit: "kegon" },
      { he: "בְּנוֹסָף", en: "in addition", translit: "benosaf" },
      { he: "מִלְּבַד", en: "apart from", translit: "milvad" },
      { he: "בִּמְקוֹם", en: "instead of", translit: "bimkom" },
      { he: "עַל יְדֵי", en: "by means of", translit: "al yedei" },
      { he: "לְגַבֵּי", en: "regarding", translit: "legabei" },
      { he: "בְּנוֹגֵעַ לְ", en: "concerning", translit: "benoge'a le" },
      { he: "מִצַּד אֶחָד", en: "on the one hand", translit: "mitsad echad" },
      { he: "לְעִתִּים", en: "at times", translit: "le'itim" },
      { he: "בְּדֶרֶךְ כְּלָל", en: "generally", translit: "bederech klal" },
      { he: "בִּפְרָט", en: "in particular", translit: "biffrat" },
      { he: "לְמַעֲשֶׂה", en: "in fact", translit: "lema'ase" },
      { he: "אֶלָּא", en: "but rather", translit: "ela" },
      { he: "אַף כִּי", en: "even though", translit: "af ki" },
      { he: "יֶתֶר עַל כֵּן", en: "moreover", translit: "yeter al ken" },
      { he: "בְּסוֹפוֹ שֶׁל דָּבָר", en: "in the end", translit: "besofo shel davar" },
      { he: "מִשּׁוּם שֶׁ", en: "because", translit: "mishum she" },
      { he: "כְּפִי שֶׁ", en: "as, according to", translit: "kfi she" },
      { he: "הוֹאִיל וְ", en: "since, whereas", translit: "ho'il ve" },
    ],
  },
  {
    id: "vsociety", level: 5, after: "s5",
    title: "Society and argument",
    titleHe: "חֶבְרָה וְעִיּוּן",
    goal: "The nouns of politics, history and criticism.",
    note: "This is the register of the essays in the library — Ahad Ha'am, Berdyczewski, Brenner arguing about what a nation is. Nearly all of it is abstract and nearly none of it is in a phrasebook.",
    words: [
      { he: "מֶמְשָׁלָה", en: "government", translit: "memshala" },
      { he: "שִׁלְטוֹן", en: "rule, regime", translit: "shilton" },
      { he: "חֹק", en: "law", translit: "chok" },
      { he: "זְכוּת", en: "right, privilege", translit: "zchut" },
      { he: "חוֹבָה", en: "duty, obligation", translit: "chova" },
      { he: "מַהְפֵּכָה", en: "revolution", translit: "mahpecha" },
      { he: "תְּנוּעָה", en: "movement", translit: "tnu'a" },
      { he: "מַאֲבָק", en: "struggle", translit: "ma'avak" },
      { he: "שִׁנּוּי", en: "change", translit: "shinuy" },
      { he: "הִתְפַּתְּחוּת", en: "development", translit: "hitpatchut" },
      { he: "תַּרְבּוּת", en: "culture", translit: "tarbut" },
      { he: "מָסֹרֶת", en: "tradition", translit: "masoret" },
      { he: "דָּת", en: "religion", translit: "dat" },
      { he: "אֱמוּנָה", en: "belief, faith", translit: "emuna" },
      { he: "מַדָּע", en: "science", translit: "mada" },
      { he: "פִילוֹסוֹפְיָה", en: "philosophy", translit: "filosofya" },
      { he: "סִפְרוּת", en: "literature", translit: "sifrut" },
      { he: "בִּקֹּרֶת", en: "criticism", translit: "bikoret" },
      { he: "דֵּעָה", en: "opinion", translit: "de'a" },
      { he: "טַעֲנָה", en: "claim, argument", translit: "ta'ana" },
      { he: "הוֹכָחָה", en: "proof", translit: "hochacha" },
      { he: "סְפֵק", en: "doubt", translit: "sfek" },
      { he: "שְׁאֵלָה", en: "question, issue", translit: "she'ela" },
      { he: "בְּעָיָה", en: "problem", translit: "be'aya" },
      { he: "פִּתְרוֹן", en: "solution", translit: "pitaron" },
      { he: "מַסְקָנָה", en: "conclusion", translit: "maskana" },
      { he: "הַשְׁפָּעָה", en: "influence", translit: "hashpa'a" },
      { he: "מַשְׁמָעוּת", en: "meaning, significance", translit: "mashma'ut" },
      { he: "יַחַס", en: "attitude, relation", translit: "yachas" },
      { he: "עֻבְדָּה", en: "fact", translit: "uvda" },
    ],
  },
  {
    id: "vrab", level: 6, after: "l3",
    title: "Rabbinic Hebrew and its Aramaic",
    titleHe: "לְשׁוֹן חֲכָמִים",
    goal: "The words and abbreviations that fill a page of commentary.",
    note: "Rabbinic Hebrew borrows heavily from Aramaic, and prints it in abbreviations. A page of commentary is unreadable without these and straightforward with them.",
    words: [
      { he: "מִשְׁנָה", en: "Mishnah, teaching", translit: "mishna" },
      { he: "גְּמָרָא", en: "Gemara", translit: "gmara" },
      { he: "הֲלָכָה", en: "law, ruling", translit: "halacha" },
      { he: "אַגָּדָה", en: "narrative, legend", translit: "agada" },
      { he: "מִדְרָשׁ", en: "midrash, exposition", translit: "midrash" },
      { he: "פֵּרוּשׁ", en: "commentary, meaning", translit: "perush" },
      { he: "מַסֶּכֶת", en: "tractate", translit: "masechet" },
      { he: "רַב", en: "rabbi, great", translit: "rav" },
      { he: "תַּנָּא", en: "a sage of the Mishnah", translit: "tana" },
      { he: "אָמוֹרָא", en: "a sage of the Gemara", translit: "amora" },
      { he: "מַאי", en: "what (Aramaic)", translit: "mai" },
      { he: "אָמַר לֵיהּ", en: "he said to him (Aramaic)", translit: "amar leih" },
      { he: "הָכִי", en: "thus (Aramaic)", translit: "hachi" },
      { he: "מִלְּתָא", en: "matter, thing (Aramaic)", translit: "milta" },
      { he: "לְמֵימַר", en: "to say (Aramaic)", translit: "lemeimar" },
      { he: "תָּא שְׁמַע", en: "come and hear", translit: "ta shma" },
      { he: "קַל וָחֹמֶר", en: "all the more so", translit: "kal vachomer" },
      { he: "כִּדְאָמְרִינַן", en: "as we said", translit: "kid'amrinan" },
      { he: "וְכוּלֵּי", en: "et cetera (וכו׳)", translit: "vechulei" },
      { he: "כְּלוֹמַר", en: "that is to say (כלומר)", translit: "klomar" },
      { he: "רָאשֵׁי תֵּבוֹת", en: "initials, abbreviation", translit: "rashei tevot" },
      { he: "עַיֵּן שָׁם", en: "see there (עי״ש)", translit: "ayen sham" },
      { he: "זִכְרוֹנוֹ לִבְרָכָה", en: "of blessed memory (ז״ל)", translit: "zichrono livracha" },
      { he: "עַל פִּי", en: "according to", translit: "al pi" },
      { he: "בְּיָדוּעַ", en: "it is known", translit: "beyadu'a" },
    ],
  },
];
