/* Themed vocabulary — the sets the first three files left out.

   The packs before this one teach the room you're standing in and the words an
   argument is made of. These are the ones a reader trips over instead: the
   fixed phrases nobody translates word by word, the year a Hebrew book counts
   its months by, the vocabulary the last hundred years added, and the two
   registers the library keeps returning to — the road out and the kingdom. */

export const PACKS_4 = [
  {
    id: "vphrase", level: 2, after: "a8",
    title: "What people actually say",
    titleHe: "בִּטּוּיִים",
    goal: "The fixed phrases — greetings, wishes, and the small change of a conversation.",
    note: "None of these is worth taking apart. בְּתֵאָבוֹן is not a sentence you build, it is a noise you make when food arrives, and every language has thirty of them. Learn them whole and use them on day one.",
    words: [
      { he: "מַה שְּׁלוֹמְךָ", en: "how are you (m.)", translit: "ma shlomcha" },
      { he: "מַה שְּׁלוֹמֵךְ", en: "how are you (f.)", translit: "ma shlomech" },
      { he: "מַה נִּשְׁמָע", en: "what's new, how's it going", translit: "ma nishma" },
      { he: "בְּסֵדֶר", en: "okay, fine", translit: "beseder" },
      { he: "אֵין בְּעָיָה", en: "no problem", translit: "ein be'aya" },
      { he: "נָעִים מְאֹד", en: "pleased to meet you", translit: "na'im me'od" },
      { he: "נָעִים לְהַכִּיר", en: "nice to meet you", translit: "na'im lehakir" },
      { he: "אֵיךְ קוֹרְאִים לְךָ", en: "what's your name (m.)", translit: "eich kor'im lecha" },
      { he: "בְּהַצְלָחָה", en: "good luck", translit: "behatslacha" },
      { he: "בְּתֵאָבוֹן", en: "enjoy your meal", translit: "bete'avon" },
      { he: "לְחַיִּים", en: "cheers — to life", translit: "lechayim" },
      { he: "מַזָּל טוֹב", en: "congratulations", translit: "mazal tov" },
      { he: "כָּל הַכָּבוֹד", en: "well done", translit: "kol hakavod" },
      { he: "תִּתְחַדֵּשׁ", en: "enjoy the new one", translit: "titchadesh" },
      { he: "בָּרוּךְ הַבָּא", en: "welcome (to a man)", translit: "baruch haba" },
      { he: "בְּרוּכָה הַבָּאָה", en: "welcome (to a woman)", translit: "brucha haba'a" },
      { he: "שָׁנָה טוֹבָה", en: "happy new year", translit: "shana tova" },
      { he: "חַג שָׂמֵחַ", en: "happy holiday", translit: "chag same'ach" },
      { he: "שַׁבָּת שָׁלוֹם", en: "a peaceful Sabbath", translit: "shabat shalom" },
      { he: "עֶרֶב טוֹב", en: "good evening", translit: "erev tov" },
      { he: "לַיְלָה טוֹב", en: "good night", translit: "layla tov" },
      { he: "מַה קָּרָה", en: "what happened, what's wrong", translit: "ma kara" },
      { he: "לֹא נוֹרָא", en: "never mind, it's not so bad", translit: "lo nora" },
      { he: "חֲבָל", en: "what a shame", translit: "chaval" },
      { he: "כַּמּוּבָן", en: "of course", translit: "kamuvan" },
      { he: "בֶּאֱמֶת", en: "really, truly", translit: "be'emet" },
      { he: "תֵּכֶף", en: "in a moment", translit: "techef" },
      { he: "דַּי", en: "enough, stop it", translit: "dai" },
    ],
  },
  {
    id: "vholiday", level: 3, after: "b12",
    title: "The Jewish year",
    titleHe: "חַגִּים",
    goal: "The festivals, and the objects and words that belong to each.",
    note: "The calendar pack gave you the months. This gives you what happens in them — and it is not optional vocabulary for a reader: a public-domain Hebrew library is a library of people whose year ran on these days, and half of what they allude to lives here.",
    words: [
      { he: "מוֹעֵד", en: "an appointed festival", translit: "mo'ed" },
      { he: "יוֹם טוֹב", en: "a festival day", translit: "yom tov" },
      { he: "חֹל הַמּוֹעֵד", en: "the middle days of a festival", translit: "chol hamo'ed" },
      { he: "יוֹם כִּפּוּר", en: "the Day of Atonement", translit: "yom kipur" },
      { he: "סְלִיחוֹת", en: "the penitential prayers", translit: "slichot" },
      { he: "שׁוֹפָר", en: "ram's horn", translit: "shofar" },
      { he: "צוֹם", en: "a fast", translit: "tsom" },
      { he: "סֻכָּה", en: "a booth", translit: "suka" },
      { he: "לוּלָב", en: "palm frond", translit: "lulav" },
      { he: "אֶתְרוֹג", en: "citron", translit: "etrog" },
      { he: "חֲנֻכִּיָּה", en: "Hanukkah lamp", translit: "chanukiya" },
      { he: "סְבִיבוֹן", en: "spinning top", translit: "sevivon" },
      { he: "פּוּרִים", en: "Purim", translit: "purim" },
      { he: "מְגִלָּה", en: "a scroll", translit: "megila" },
      { he: "מִשְׁלוֹחַ מָנוֹת", en: "gifts of food sent at Purim", translit: "mishloach manot" },
      { he: "מַצָּה", en: "unleavened bread", translit: "matsa" },
      { he: "סֵדֶר", en: "the Passover meal — an order", translit: "seder" },
      { he: "הַגָּדָה", en: "the text read at the Seder", translit: "hagada" },
      { he: "שָׁבוּעוֹת", en: "Shavuot, the feast of weeks", translit: "shavuot" },
      { he: "תִּשְׁעָה בְּאָב", en: "the ninth of Av, a day of mourning", translit: "tish'a be'av" },
      { he: "נֵר", en: "candle", translit: "ner" },
      { he: "קִדּוּשׁ", en: "the blessing over wine", translit: "kidush" },
      { he: "הַבְדָּלָה", en: "the ceremony closing the Sabbath", translit: "havdala" },
      { he: "חַלָּה", en: "Sabbath loaf", translit: "chala" },
      { he: "סִדּוּר", en: "prayer book", translit: "sidur" },
      { he: "טַלִּית", en: "prayer shawl", translit: "talit" },
      { he: "מְזוּזָה", en: "the scroll on a doorpost", translit: "mezuza" },
      { he: "מִנְיָן", en: "a quorum of ten", translit: "minyan" },
      { he: "בַּר מִצְוָה", en: "coming of age at thirteen", translit: "bar mitsva" },
      { he: "חֻפָּה", en: "wedding canopy", translit: "chupa" },
      { he: "כָּשֵׁר", en: "fit to eat, kosher", translit: "kasher" },
    ],
  },
  {
    id: "vtech", level: 3, after: "b8",
    title: "The last hundred years",
    titleHe: "הָעוֹלָם הֶחָדָשׁ",
    goal: "Screens, wires, engines and the press — the words Hebrew had to invent.",
    note: "Almost every word here was coined, most of them from a root that already existed: חַשְׁמַל was a word in Ezekiel nobody could translate before it was handed to electricity, and מַדְפֶּסֶת is just the מַקְטֵלָה instrument pattern poured over ד־פ־ס, to print.",
    words: [
      { he: "אִינְטֶרְנֶט", en: "the internet", translit: "internet" },
      { he: "אֲתָר", en: "a website, a site", translit: "atar" },
      { he: "מָסָךְ", en: "screen", translit: "masach" },
      { he: "מִקְלֶדֶת", en: "keyboard", translit: "mikledet" },
      { he: "סִיסְמָה", en: "password", translit: "sisma" },
      { he: "קֹבֶץ", en: "a file", translit: "kovets" },
      { he: "תָּכְנָה", en: "software", translit: "tochna" },
      { he: "מַדְפֶּסֶת", en: "printer", translit: "madpeset" },
      { he: "כַּפְתּוֹר", en: "a button", translit: "kaftor" },
      { he: "חִבּוּר", en: "a connection", translit: "chibur" },
      { he: "רֶשֶׁת", en: "a net, a network", translit: "reshet" },
      { he: "סוֹלְלָה", en: "battery", translit: "solela" },
      { he: "חַשְׁמַל", en: "electricity", translit: "chashmal" },
      { he: "מָנוֹעַ", en: "engine", translit: "mano'a" },
      { he: "מְכוֹנָה", en: "a machine", translit: "mechona" },
      { he: "תְּמוּנָה", en: "a picture", translit: "tmuna" },
      { he: "סֶרֶט", en: "a film, a ribbon", translit: "seret" },
      { he: "טֶלֶוִיזְיָה", en: "television", translit: "televizya" },
      { he: "רַדְיוֹ", en: "radio", translit: "radyo" },
      { he: "עִתּוֹן", en: "newspaper", translit: "iton" },
      { he: "חֲדָשׁוֹת", en: "the news", translit: "chadashot" },
      { he: "פִּרְסֹמֶת", en: "an advertisement", translit: "pirsomet" },
      { he: "הוֹדָעָה", en: "a message, a notice", translit: "hoda'a" },
      { he: "שִׂיחָה", en: "a conversation, a call", translit: "sicha" },
    ],
  },
  {
    id: "vroad", level: 5, after: "s5",
    title: "The road out",
    titleHe: "דֶּרֶךְ",
    goal: "Journeys, ships, borders and exile — the register modern Hebrew literature lives in.",
    note: "Leaving is the subject of an enormous share of the shelf: a village left behind, a port, a crossing, a homeland arrived at or lost. These are the words that carry it, and they turn up in poetry as readily as in a train timetable.",
    words: [
      { he: "דֶּרֶךְ", en: "road, way", translit: "derech" },
      { he: "שְׁבִיל", en: "path", translit: "shvil" },
      { he: "מַסָּע", en: "a journey", translit: "masa" },
      { he: "מוֹלֶדֶת", en: "homeland", translit: "moledet" },
      { he: "גָּלוּת", en: "exile", translit: "galut" },
      { he: "גּוֹלֶה", en: "an exile, one banished", translit: "gole" },
      { he: "מְהַגֵּר", en: "an emigrant", translit: "mehager" },
      { he: "עֲלִיָּה", en: "an ascent — immigration to the land", translit: "aliya" },
      { he: "גְּבוּל", en: "border", translit: "gvul" },
      { he: "צָפוֹן", en: "north", translit: "tsafon" },
      { he: "דָּרוֹם", en: "south", translit: "darom" },
      { he: "מִזְרָח", en: "east", translit: "mizrach" },
      { he: "מַעֲרָב", en: "west", translit: "ma'arav" },
      { he: "אֳנִיָּה", en: "ship", translit: "oniya" },
      { he: "סִירָה", en: "boat", translit: "sira" },
      { he: "מִפְרָשׂ", en: "sail", translit: "mifras" },
      { he: "נָמָל", en: "port", translit: "namal" },
      { he: "חוֹף", en: "shore", translit: "chof" },
      { he: "מַלָּח", en: "sailor", translit: "malach" },
      { he: "נְדוּדִים", en: "wanderings", translit: "nedudim" },
      { he: "אֹהֶל", en: "tent", translit: "ohel" },
      { he: "פֻּנְדָּק", en: "an inn", translit: "pundak" },
      { he: "עֲגָלָה", en: "a cart", translit: "agala" },
      { he: "תַּרְמִיל", en: "knapsack", translit: "tarmil" },
      { he: "תַּיָּר", en: "a tourist", translit: "tayar" },
      { he: "פְּרֵדָה", en: "a parting, farewell", translit: "preda" },
    ],
  },
  {
    id: "vwar", level: 6, after: "l1",
    title: "Kings, prophets and war",
    titleHe: "מְלָכִים",
    goal: "The vocabulary of the narrative books — and of everything written in their shadow.",
    note: "This set is worth more than its size suggests. A page of biblical narrative is built from a few hundred words used over and over, and these are most of the nouns among them; the rest is the vav that flips the tense.",
    words: [
      { he: "מַלְכָּה", en: "queen", translit: "malka" },
      { he: "מַמְלָכָה", en: "kingdom", translit: "mamlacha" },
      { he: "כֶּתֶר", en: "crown", translit: "keter" },
      { he: "שַׂר", en: "a minister, an officer", translit: "sar" },
      { he: "שָׁלָל", en: "spoil, plunder", translit: "shalal" },
      { he: "שֵׁבֶט", en: "a tribe — also a rod", translit: "shevet" },
      { he: "צָבָא", en: "army", translit: "tsava" },
      { he: "גִּבּוֹר", en: "a hero, a mighty man", translit: "gibor" },
      { he: "חֶרֶב", en: "sword", translit: "cherev" },
      { he: "קֶשֶׁת", en: "a bow — also a rainbow", translit: "keshet" },
      { he: "חֵץ", en: "arrow", translit: "chets" },
      { he: "מָגֵן", en: "shield", translit: "magen" },
      { he: "חוֹמָה", en: "a city wall", translit: "choma" },
      { he: "מִגְדָּל", en: "tower", translit: "migdal" },
      { he: "שַׁעַר", en: "gate", translit: "sha'ar" },
      { he: "מַחֲנֶה", en: "camp", translit: "machane" },
      { he: "נִצָּחוֹן", en: "victory", translit: "nitsachon" },
      { he: "מַפָּלָה", en: "defeat", translit: "mapala" },
      { he: "אוֹיֵב", en: "enemy", translit: "oyev" },
      { he: "שְׁבִי", en: "captivity", translit: "shvi" },
      { he: "גְּאֻלָּה", en: "redemption", translit: "ge'ula" },
      { he: "שׁוֹפֵט", en: "a judge, a ruler", translit: "shofet" },
      { he: "שָׁלִיחַ", en: "an emissary", translit: "shaliach" },
      { he: "נֶדֶר", en: "a vow", translit: "neder" },
      { he: "שְׁבוּעָה", en: "an oath", translit: "shvu'a" },
      { he: "קְלָלָה", en: "a curse", translit: "klala" },
      { he: "מִזְבֵּחַ", en: "altar", translit: "mizbe'ach" },
    ],
  },
];
