/* Themed vocabulary — the concrete half.

   Grammar lessons carry the words their examples need, which is about seven
   apiece: enough to demonstrate a rule, nowhere near enough to say anything.
   These are the sets an ulpan drills alongside the grammar — the house, the
   body, the market — and they are where most of a beginner's vocabulary
   actually comes from.

   Each pack becomes a lesson of its own, spliced into its level after the
   grammar lesson it depends on. `after` is that lesson's id. */

export const PACKS_1 = [
  {
    id: "vfam", level: 2, after: "a3",
    title: "Family and people",
    titleHe: "מִשְׁפָּחָה",
    goal: "Name everyone at the table — and notice which words come in gendered pairs.",
    note: "Hebrew kinship terms almost all come in pairs: change the ending and you change the relative. Learn them two at a time.",
    words: [
      { he: "אַבָּא", en: "dad", translit: "aba" },
      { he: "אִמָּא", en: "mum", translit: "ima" },
      { he: "אָב", en: "father", translit: "av" },
      { he: "אֵם", en: "mother", translit: "em" },
      { he: "הוֹרִים", en: "parents", translit: "horim" },
      { he: "בֵּן", en: "son", translit: "ben" },
      { he: "בַּת", en: "daughter", translit: "bat" },
      { he: "אָח", en: "brother", translit: "ach" },
      { he: "אָחוֹת", en: "sister", translit: "achot" },
      { he: "סַבָּא", en: "grandfather", translit: "saba" },
      { he: "סַבְתָּא", en: "grandmother", translit: "savta" },
      { he: "נֶכֶד", en: "grandson", translit: "neched" },
      { he: "נֶכְדָּה", en: "granddaughter", translit: "nechda" },
      { he: "דּוֹד", en: "uncle", translit: "dod" },
      { he: "דּוֹדָה", en: "aunt", translit: "doda" },
      { he: "בֶּן דּוֹד", en: "cousin (m.)", translit: "ben dod" },
      { he: "בַּעַל", en: "husband", translit: "ba'al" },
      { he: "אִשָּׁה", en: "wife, woman", translit: "isha" },
      { he: "חָתָן", en: "groom", translit: "chatan" },
      { he: "כַּלָּה", en: "bride", translit: "kala" },
      { he: "תִּינוֹק", en: "baby", translit: "tinok" },
      { he: "נַעַר", en: "youth, boy", translit: "na'ar" },
      { he: "זָקֵן", en: "old man, elder", translit: "zaken" },
      { he: "שָׁכֵן", en: "neighbour", translit: "shachen" },
      { he: "אוֹרֵחַ", en: "guest", translit: "oreach" },
      { he: "יְלָדִים", en: "children", translit: "yeladim" },
    ],
  },
  {
    id: "vhome", level: 2, after: "a5",
    title: "The house",
    titleHe: "בַּיִת",
    goal: "Name the rooms and what's in them.",
    note: "Almost every word here is a noun with a clear gender, so it's the natural place to practise the adjectives from the last lesson.",
    words: [
      { he: "דִּירָה", en: "apartment", translit: "dira" },
      { he: "חֶדֶר", en: "room", translit: "cheder" },
      { he: "מִטְבָּח", en: "kitchen", translit: "mitbach" },
      { he: "סָלוֹן", en: "living room", translit: "salon" },
      { he: "חֲדַר שֵׁנָה", en: "bedroom", translit: "chadar sheina" },
      { he: "אַמְבַּטְיָה", en: "bathroom, bath", translit: "ambatya" },
      { he: "מִרְפֶּסֶת", en: "balcony", translit: "mirpeset" },
      { he: "גִּנָּה", en: "garden", translit: "gina" },
      { he: "רִצְפָּה", en: "floor", translit: "ritspa" },
      { he: "קִיר", en: "wall", translit: "kir" },
      { he: "תִּקְרָה", en: "ceiling", translit: "tikra" },
      { he: "מַדְרֵגוֹת", en: "stairs", translit: "madregot" },
      { he: "מַעֲלִית", en: "lift, elevator", translit: "ma'alit" },
      { he: "מִטָּה", en: "bed", translit: "mita" },
      { he: "כִּסֵּא", en: "chair", translit: "kise" },
      { he: "סַפָּה", en: "sofa", translit: "sapa" },
      { he: "אָרוֹן", en: "cupboard, wardrobe", translit: "aron" },
      { he: "מַדָּף", en: "shelf", translit: "madaf" },
      { he: "מַרְאָה", en: "mirror", translit: "mar'a" },
      { he: "מְנוֹרָה", en: "lamp", translit: "menora" },
      { he: "שָׁטִיחַ", en: "carpet", translit: "shatiach" },
      { he: "מַפְתֵּחַ", en: "key", translit: "mafteach" },
      { he: "מְקָרֵר", en: "fridge", translit: "mekarer" },
      { he: "תַּנּוּר", en: "oven", translit: "tanur" },
      { he: "מְנַקֶּה", en: "cleans", translit: "menake" },
      { he: "גָּר", en: "lives, resides", translit: "gar" },
    ],
  },
  {
    id: "vfood", level: 2, after: "a7",
    title: "Food and drink",
    titleHe: "אֹכֶל וּשְׁתִיָּה",
    goal: "Order a meal and shop for one.",
    note: "Food words are where the prepositions get their workout: bread with butter, coffee without sugar, a table for two.",
    words: [
      { he: "אֹכֶל", en: "food", translit: "ochel" },
      { he: "לֶחֶם", en: "bread", translit: "lechem" },
      { he: "חָלָב", en: "milk", translit: "chalav" },
      { he: "גְּבִינָה", en: "cheese", translit: "gvina" },
      { he: "בֵּיצָה", en: "egg", translit: "beitsa" },
      { he: "בָּשָׂר", en: "meat", translit: "basar" },
      { he: "עוֹף", en: "chicken, fowl", translit: "of" },
      { he: "אֹרֶז", en: "rice", translit: "orez" },
      { he: "פֵּרוֹת", en: "fruit", translit: "perot" },
      { he: "יְרָקוֹת", en: "vegetables", translit: "yerakot" },
      { he: "תַּפּוּחַ", en: "apple", translit: "tapuach" },
      { he: "תַּפּוּז", en: "orange", translit: "tapuz" },
      { he: "עֲנָבִים", en: "grapes", translit: "anavim" },
      { he: "עַגְבָנִיָּה", en: "tomato", translit: "agvaniya" },
      { he: "מְלָפְפוֹן", en: "cucumber", translit: "melafefon" },
      { he: "בָּצָל", en: "onion", translit: "batsal" },
      { he: "מֶלַח", en: "salt", translit: "melach" },
      { he: "סֻכָּר", en: "sugar", translit: "sukar" },
      { he: "שֶׁמֶן", en: "oil", translit: "shemen" },
      { he: "חֶמְאָה", en: "butter", translit: "chem'a" },
      { he: "דְּבַשׁ", en: "honey", translit: "dvash" },
      { he: "יַיִן", en: "wine", translit: "yayin" },
      { he: "מִיץ", en: "juice", translit: "mits" },
      { he: "עוּגָה", en: "cake", translit: "uga" },
      { he: "גְּלִידָה", en: "ice cream", translit: "glida" },
      { he: "אֲרוּחָה", en: "meal", translit: "arucha" },
      { he: "מִסְעָדָה", en: "restaurant", translit: "mis'ada" },
      { he: "צַלַּחַת", en: "plate", translit: "tsalachat" },
      { he: "כּוֹס", en: "glass, cup", translit: "kos" },
      { he: "סַכִּין", en: "knife", translit: "sakin" },
      { he: "מַזְלֵג", en: "fork", translit: "mazleg" },
      { he: "טָעִים", en: "tasty", translit: "ta'im" },
      { he: "שׁוֹתֶה", en: "drinks", translit: "shote" },
      { he: "מְבַשֵּׁל", en: "cooks", translit: "mevashel" },
    ],
  },
  {
    id: "vcolour", level: 2, after: "a5",
    title: "Colours",
    titleHe: "צְבָעִים",
    goal: "Describe things by colour — and agree the adjective while you're at it.",
    note: "Colours are adjectives, so they take the same four endings as גָּדוֹל. The feminine of most of them doubles a letter: אָדֹם becomes אֲדֻמָּה.",
    words: [
      { he: "צֶבַע", en: "colour", translit: "tseva" },
      { he: "לָבָן", en: "white", translit: "lavan" },
      { he: "שָׁחֹר", en: "black", translit: "shachor" },
      { he: "אָדֹם", en: "red", translit: "adom" },
      { he: "אֲדֻמָּה", en: "red (f.)", translit: "aduma" },
      { he: "כָּחֹל", en: "blue", translit: "kachol" },
      { he: "כְּחֻלָּה", en: "blue (f.)", translit: "kchula" },
      { he: "יָרֹק", en: "green", translit: "yarok" },
      { he: "יְרֻקָּה", en: "green (f.)", translit: "yeruka" },
      { he: "צָהֹב", en: "yellow", translit: "tsahov" },
      { he: "כָּתֹם", en: "orange", translit: "katom" },
      { he: "סָגֹל", en: "purple", translit: "sagol" },
      { he: "וָרֹד", en: "pink", translit: "varod" },
      { he: "חוּם", en: "brown", translit: "chum" },
      { he: "אָפֹר", en: "grey", translit: "afor" },
      { he: "זָהָב", en: "gold", translit: "zahav" },
      { he: "כֶּסֶף", en: "silver, money", translit: "kesef" },
      { he: "בָּהִיר", en: "light, pale", translit: "bahir" },
      { he: "כֵּהֶה", en: "dark", translit: "kehe" },
    ],
  },
  {
    id: "vbody", level: 3, after: "b3",
    title: "The body, and being unwell",
    titleHe: "הַגּוּף",
    goal: "Point at what hurts.",
    note: "Body parts that come in twos take the dual ending ־ַיִם: עֵינַיִם eyes, יָדַיִם hands, רַגְלַיִם legs. It's a plural you'll meet almost nowhere else.",
    words: [
      { he: "גּוּף", en: "body", translit: "guf" },
      { he: "פָּנִים", en: "face", translit: "panim" },
      { he: "עַיִן", en: "eye", translit: "ayin" },
      { he: "עֵינַיִם", en: "eyes", translit: "einayim" },
      { he: "אֹזֶן", en: "ear", translit: "ozen" },
      { he: "אַף", en: "nose", translit: "af" },
      { he: "שֵׁן", en: "tooth", translit: "shen" },
      { he: "שְׂפָתַיִם", en: "lips", translit: "sfatayim" },
      { he: "לָשׁוֹן", en: "tongue, language", translit: "lashon" },
      { he: "צַוָּאר", en: "neck", translit: "tsavar" },
      { he: "כָּתֵף", en: "shoulder", translit: "katef" },
      { he: "יָדַיִם", en: "hands", translit: "yadayim" },
      { he: "אֶצְבַּע", en: "finger", translit: "etsba" },
      { he: "גַּב", en: "back", translit: "gav" },
      { he: "בֶּטֶן", en: "stomach, belly", translit: "beten" },
      { he: "לֵב", en: "heart", translit: "lev" },
      { he: "רֶגֶל", en: "leg, foot", translit: "regel" },
      { he: "בֶּרֶךְ", en: "knee", translit: "berech" },
      { he: "שֵׂעָר", en: "hair", translit: "se'ar" },
      { he: "עוֹר", en: "skin, leather", translit: "or" },
      { he: "עֶצֶם", en: "bone", translit: "etsem" },
      { he: "דָּם", en: "blood", translit: "dam" },
      { he: "רוֹפֵא", en: "doctor", translit: "rofe" },
      { he: "מַחֲלָה", en: "illness", translit: "machala" },
      { he: "כְּאֵב", en: "pain", translit: "ke'ev" },
      { he: "חֹם", en: "fever, heat", translit: "chom" },
      { he: "תְּרוּפָה", en: "medicine", translit: "trufa" },
      { he: "בָּרִיא", en: "healthy", translit: "bari" },
      { he: "חוֹלֶה", en: "sick, a patient", translit: "chole" },
      { he: "כּוֹאֵב", en: "hurts", translit: "ko'ev" },
    ],
  },
  {
    id: "vcity", level: 3, after: "b6",
    title: "The city, and getting about",
    titleHe: "בָּעִיר",
    goal: "Find your way and say how you got there.",
    note: "Directions use the old ־ָה ending you'll meet again in level 6: יָמִינָה rightwards, שְׂמֹאלָה leftwards.",
    words: [
      { he: "רְחוֹב", en: "street", translit: "rechov" },
      { he: "כְּבִישׁ", en: "road", translit: "kvish" },
      { he: "כִּכָּר", en: "square", translit: "kikar" },
      { he: "גֶּשֶׁר", en: "bridge", translit: "gesher" },
      { he: "בִּנְיָן", en: "building", translit: "binyan" },
      { he: "חֲנוּת", en: "shop", translit: "chanut" },
      { he: "שׁוּק", en: "market", translit: "shuk" },
      { he: "בַּנְק", en: "bank", translit: "bank" },
      { he: "דֹּאַר", en: "post, mail", translit: "do'ar" },
      { he: "בֵּית קָפֶה", en: "café", translit: "beit kafe" },
      { he: "מָלוֹן", en: "hotel", translit: "malon" },
      { he: "תַּחֲנָה", en: "station, stop", translit: "tachana" },
      { he: "אוֹטוֹבּוּס", en: "bus", translit: "otobus" },
      { he: "רַכֶּבֶת", en: "train", translit: "rakevet" },
      { he: "מְכוֹנִית", en: "car", translit: "mechonit" },
      { he: "מוֹנִית", en: "taxi", translit: "monit" },
      { he: "אוֹפַנַּיִם", en: "bicycle", translit: "ofanayim" },
      { he: "מָטוֹס", en: "aeroplane", translit: "matos" },
      { he: "כַּרְטִיס", en: "ticket", translit: "kartis" },
      { he: "מַפָּה", en: "map", translit: "mapa" },
      { he: "יָמִינָה", en: "to the right", translit: "yamina" },
      { he: "שְׂמֹאלָה", en: "to the left", translit: "smola" },
      { he: "יָשָׁר", en: "straight", translit: "yashar" },
      { he: "רָחוֹק", en: "far", translit: "rachok" },
      { he: "קָרוֹב", en: "near", translit: "karov" },
      { he: "כְּפָר", en: "village", translit: "kfar" },
      { he: "נוֹסֵעַ", en: "travels, rides", translit: "nose'a" },
      { he: "עוֹצֵר", en: "stops", translit: "otser" },
    ],
  },
  {
    id: "vshop", level: 3, after: "b7",
    title: "Clothes and shopping",
    titleHe: "בְּגָדִים וּקְנִיּוֹת",
    goal: "Buy something, and say what you're wearing.",
    note: "Paired garments take the dual too: מִכְנָסַיִם trousers, נַעֲלַיִם shoes, גַּרְבַּיִם socks — all grammatically plural, like their English names.",
    words: [
      { he: "בֶּגֶד", en: "garment", translit: "beged" },
      { he: "חֻלְצָה", en: "shirt, blouse", translit: "chultsa" },
      { he: "מִכְנָסַיִם", en: "trousers", translit: "michnasayim" },
      { he: "שִׂמְלָה", en: "dress", translit: "simla" },
      { he: "חֲצָאִית", en: "skirt", translit: "chatsa'it" },
      { he: "מְעִיל", en: "coat", translit: "me'il" },
      { he: "סְוֶדֶר", en: "sweater", translit: "sveder" },
      { he: "נַעֲלַיִם", en: "shoes", translit: "na'alayim" },
      { he: "גַּרְבַּיִם", en: "socks", translit: "garbayim" },
      { he: "כּוֹבַע", en: "hat", translit: "kova" },
      { he: "צָעִיף", en: "scarf", translit: "tsa'if" },
      { he: "חֲגוֹרָה", en: "belt", translit: "chagora" },
      { he: "תִּיק", en: "bag", translit: "tik" },
      { he: "מִשְׁקָפַיִם", en: "glasses", translit: "mishkafayim" },
      { he: "שָׁעוֹן", en: "watch, clock", translit: "sha'on" },
      { he: "טַבַּעַת", en: "ring", translit: "taba'at" },
      { he: "מְחִיר", en: "price", translit: "mechir" },
      { he: "זוֹל", en: "cheap", translit: "zol" },
      { he: "יָקָר", en: "expensive, dear", translit: "yakar" },
      { he: "מִדָּה", en: "size, measure", translit: "mida" },
      { he: "הַנָּחָה", en: "discount", translit: "hanacha" },
      { he: "לוֹבֵשׁ", en: "wears", translit: "lovesh" },
      { he: "קוֹנֶה", en: "buys", translit: "kone" },
      { he: "מוֹכֵר", en: "sells, a seller", translit: "mocher" },
      { he: "מְשַׁלֵּם", en: "pays", translit: "meshalem" },
      { he: "מִזְוָדָה", en: "suitcase", translit: "mizvada" },
    ],
  },
  {
    id: "vwork", level: 3, after: "b8",
    title: "Work and study",
    titleHe: "עֲבוֹדָה וְלִמּוּדִים",
    goal: "Say what you do and where you do it.",
    note: "Job names are nouns built from verbs: מוֹרֶה teaches and is a teacher, מוֹכֵר sells and is a seller. The present participle does both jobs.",
    words: [
      { he: "מִשְׂרָד", en: "office", translit: "misrad" },
      { he: "פּוֹעֵל", en: "worker, labourer", translit: "po'el" },
      { he: "מְנַהֵל", en: "manager", translit: "menahel" },
      { he: "מְהַנְדֵּס", en: "engineer", translit: "mehandes" },
      { he: "תַּלְמִיד", en: "pupil", translit: "talmid" },
      { he: "אוּנִיבֶרְסִיטָה", en: "university", translit: "universita" },
      { he: "כִּתָּה", en: "classroom, class", translit: "kita" },
      { he: "שִׁעוּר", en: "lesson", translit: "shi'ur" },
      { he: "מִבְחָן", en: "exam", translit: "mivchan" },
      { he: "תְּעוּדָה", en: "certificate", translit: "te'uda" },
      { he: "מַשְׂכֹּרֶת", en: "salary", translit: "maskoret" },
      { he: "פְּגִישָׁה", en: "meeting", translit: "pgisha" },
      { he: "מַחְשֵׁב", en: "computer", translit: "machshev" },
      { he: "טֶלֶפוֹן", en: "telephone", translit: "telefon" },
      { he: "עֵט", en: "pen", translit: "et" },
      { he: "עִפָּרוֹן", en: "pencil", translit: "iparon" },
      { he: "נְיָר", en: "paper", translit: "neyar" },
      { he: "שְׁאֵלָה", en: "question", translit: "she'ela" },
      { he: "תְּשׁוּבָה", en: "answer", translit: "tshuva" },
      { he: "מִקְצוֹעַ", en: "profession", translit: "miktso'a" },
      { he: "חֶבְרָה", en: "company, society", translit: "chevra" },
      { he: "מְנַסֶּה", en: "tries", translit: "menase" },
      { he: "מַצְלִיחַ", en: "succeeds", translit: "matsliach" },
      { he: "נִכְשָׁל", en: "fails", translit: "nichshal" },
    ],
  },
  {
    id: "vnature", level: 3, after: "b9",
    title: "Weather and the natural world",
    titleHe: "טֶבַע וּמֶזֶג אֲוִיר",
    goal: "Talk about the weather, the seasons and the landscape.",
    note: "Weather is stated with the bare adjective and no verb: חַם הַיּוֹם, it's hot today — literally hot the day.",
    words: [
      { he: "מֶזֶג אֲוִיר", en: "weather", translit: "mezeg avir" },
      { he: "יָרֵחַ", en: "moon", translit: "yare'ach" },
      { he: "כּוֹכָב", en: "star", translit: "kochav" },
      { he: "עָנָן", en: "cloud", translit: "anan" },
      { he: "גֶּשֶׁם", en: "rain", translit: "geshem" },
      { he: "שֶׁלֶג", en: "snow", translit: "sheleg" },
      { he: "רוּחַ", en: "wind, spirit", translit: "ru'ach" },
      { he: "סַעֲרָה", en: "storm", translit: "se'ara" },
      { he: "חַם", en: "hot", translit: "cham" },
      { he: "קַר", en: "cold", translit: "kar" },
      { he: "נָעִים", en: "pleasant", translit: "na'im" },
      { he: "אֲוִיר", en: "air", translit: "avir" },
      { he: "אֵשׁ", en: "fire", translit: "esh" },
      { he: "אֲדָמָה", en: "earth, ground", translit: "adama" },
      { he: "הַר", en: "mountain", translit: "har" },
      { he: "עֵמֶק", en: "valley", translit: "emek" },
      { he: "נָהָר", en: "river", translit: "nahar" },
      { he: "יָם", en: "sea", translit: "yam" },
      { he: "מִדְבָּר", en: "desert, wilderness", translit: "midbar" },
      { he: "יַעַר", en: "forest", translit: "ya'ar" },
      { he: "פֶּרַח", en: "flower", translit: "perach" },
      { he: "עָלֶה", en: "leaf", translit: "ale" },
      { he: "דֶּשֶׁא", en: "grass", translit: "deshe" },
      { he: "חוֹל", en: "sand", translit: "chol" },
      { he: "אָבִיב", en: "spring", translit: "aviv" },
      { he: "קַיִץ", en: "summer", translit: "kayits" },
      { he: "סְתָו", en: "autumn", translit: "stav" },
      { he: "חֹרֶף", en: "winter", translit: "choref" },
      { he: "עוֹנָה", en: "season", translit: "ona" },
    ],
  },
  {
    id: "vanimal", level: 3, after: "b9",
    title: "Animals",
    titleHe: "בַּעֲלֵי חַיִּים",
    goal: "Name the animals — and read the fables the library is full of.",
    note: "Fables are the easiest literature in the corpus and they are entirely animals. Fifteen of these words unlock most of them.",
    words: [
      { he: "בַּעַל חַיִּים", en: "animal", translit: "ba'al chayim" },
      { he: "חָתוּל", en: "cat", translit: "chatul" },
      { he: "סוּס", en: "horse", translit: "sus" },
      { he: "פָּרָה", en: "cow", translit: "para" },
      { he: "שׁוֹר", en: "ox", translit: "shor" },
      { he: "כֶּבֶשׂ", en: "sheep, lamb", translit: "keves" },
      { he: "עֵז", en: "goat", translit: "ez" },
      { he: "חֲמוֹר", en: "donkey", translit: "chamor" },
      { he: "גָּמָל", en: "camel", translit: "gamal" },
      { he: "אַרְיֵה", en: "lion", translit: "arye" },
      { he: "דֹּב", en: "bear", translit: "dov" },
      { he: "זְאֵב", en: "wolf", translit: "ze'ev" },
      { he: "שׁוּעָל", en: "fox", translit: "shu'al" },
      { he: "צִפּוֹר", en: "bird", translit: "tsipor" },
      { he: "נֶשֶׁר", en: "eagle, vulture", translit: "nesher" },
      { he: "יוֹנָה", en: "dove", translit: "yona" },
      { he: "תַּרְנְגֹלֶת", en: "hen", translit: "tarnegolet" },
      { he: "נָחָשׁ", en: "snake", translit: "nachash" },
      { he: "עַכְבָּר", en: "mouse", translit: "achbar" },
      { he: "דְּבוֹרָה", en: "bee", translit: "dvora" },
      { he: "נְמָלָה", en: "ant", translit: "nemala" },
      { he: "פַּרְפַּר", en: "butterfly", translit: "parpar" },
      { he: "כָּנָף", en: "wing", translit: "kanaf" },
      { he: "זָנָב", en: "tail", translit: "zanav" },
    ],
  },
];
