/* Downloads the Hebrew + Latin subsets of Frank Ruhl Libre and Rubik from
   Google Fonts into src/assets/fonts/ and rewrites src/fonts.css to serve
   them locally. Run once (or after changing weights):  node scripts/fetch-fonts.mjs
   Both families are licensed under the SIL Open Font License. */

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = join(root, "src", "assets", "fonts");
mkdirSync(fontDir, { recursive: true });

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@400;500;700&family=Rubik:wght@400;500;600;700&display=swap";
/* A modern UA makes Google serve woff2 with unicode-range subsets */
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const curl = (url, outFile) => {
  const args = ["-sSfL", "-A", UA, url];
  if (outFile) args.push("-o", outFile);
  return execFileSync("curl", args, { encoding: outFile ? "buffer" : "utf8" });
};

const css = curl(CSS_URL);

/* Parse: comment naming the subset, then the @font-face block */
const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
const WANTED_SUBSETS = new Set(["hebrew", "latin"]);
const faces = [];
let m;
while ((m = blockRe.exec(css)) !== null) {
  const subset = m[1];
  if (!WANTED_SUBSETS.has(subset)) continue;
  const body = m[2];
  const family = body.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
  const style = body.match(/font-style:\s*(\w+)/)?.[1] || "normal";
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (!family || !weight || !url) continue;
  faces.push({ subset, family, weight, style, url, range });
}

if (faces.length === 0) {
  console.error("No font faces parsed — Google Fonts CSS format may have changed.");
  process.exit(1);
}

const rules = [];
for (const f of faces) {
  const slug = `${f.family.toLowerCase().replace(/\s+/g, "-")}-${f.weight}-${f.subset}.woff2`;
  curl(f.url, join(fontDir, slug));
  rules.push(
    `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./assets/fonts/${slug}') format('woff2');${f.range ? `\n  unicode-range: ${f.range};` : ""}
}`
  );
  console.log(`saved ${slug}`);
}

const header = `/* Self-hosted webfonts (SIL Open Font License):
   Frank Ruhl Libre — Hebrew serif for the reading text
   Rubik — UI face (Hebrew + Latin)
   Generated by scripts/fetch-fonts.mjs — edit that script, not this file. */\n\n`;

writeFileSync(join(root, "src", "fonts.css"), header + rules.join("\n\n") + "\n");
console.log(`Wrote src/fonts.css with ${rules.length} @font-face rules.`);
