/* Built-in story — "Lavan", an original A1-level graded reader */

export const CHAPTERS = [
  {
    num: "א׳",
    titleHe: "דָּנִי גָּר בְּתֵל אָבִיב",
    titleEn: "Dani Lives in Tel Aviv",
    sentences: [
      { he: "דָּנִי גָּר בְּתֵל אָבִיב.", en: "Dani lives in Tel Aviv." },
      { he: "הוּא גָּר בְּדִירָה קְטַנָּה בִּרְחוֹב דִּיזֶנְגּוֹף.", en: "He lives in a small apartment on Dizengoff Street." },
      { he: "בַּבֹּקֶר הוּא שׁוֹתֶה קָפֶה בַּמִּרְפֶּסֶת.", en: "In the morning he drinks coffee on the balcony." },
      { he: "הוּא אוֹהֵב אֶת הָעִיר.", en: "He loves the city." },
      { he: "הָרְחוֹב מָלֵא אֲנָשִׁים, אוֹפַנַּיִם וַחֲתוּלִים.", en: "The street is full of people, bicycles, and cats." },
      { he: "בְּתֵל אָבִיב יֵשׁ הַרְבֵּה חֲתוּלִים.", en: "In Tel Aviv there are many cats." },
      { he: "דָּנִי רוֹאֶה אוֹתָם כָּל יוֹם.", en: "Dani sees them every day." },
    ],
    questions: [
      { q: "Where does Dani live?", opts: ["In a big house in Jerusalem", "In a small apartment on Dizengoff Street", "In a hotel by the beach", "On a kibbutz in the north"], correct: 1, ev: "הוּא גָּר בְּדִירָה קְטַנָּה בִּרְחוֹב דִּיזֶנְגּוֹף." },
      { q: "What does Dani do every morning?", opts: ["Rides his bicycle to work", "Feeds the street cats", "Drinks coffee on the balcony", "Goes to the market"], correct: 2, ev: "בַּבֹּקֶר הוּא שׁוֹתֶה קָפֶה בַּמִּרְפֶּסֶת." },
      { q: "According to the story, what is there a lot of in Tel Aviv?", opts: ["Dogs", "Cats", "Coffee shops", "Tourists"], correct: 1, ev: "בְּתֵל אָבִיב יֵשׁ הַרְבֵּה חֲתוּלִים." },
    ],
  },
  {
    num: "ב׳",
    titleHe: "קוֹל קָטָן בָּרְחוֹב",
    titleEn: "A Small Sound in the Street",
    sentences: [
      { he: "יוֹם אֶחָד, דָּנִי הוֹלֵךְ לַשּׁוּק.", en: "One day, Dani walks to the market." },
      { he: "פִּתְאוֹם הוּא שׁוֹמֵעַ קוֹל קָטָן.", en: "Suddenly he hears a small sound." },
      { he: "מִיָּאוּ! מִיָּאוּ!", en: "Meow! Meow!" },
      { he: "לְיַד הַחֲנוּת יוֹשֵׁב חָתוּל קָטָן וְלָבָן.", en: "Next to the shop sits a small white cat." },
      { he: "הֶחָתוּל רָעֵב מְאוֹד.", en: "The cat is very hungry." },
      { he: "דָּנִי מִסְתַּכֵּל עַל הֶחָתוּל, וְהֶחָתוּל מִסְתַּכֵּל עַל דָּנִי.", en: "Dani looks at the cat, and the cat looks at Dani." },
      { he: "״שָׁלוֹם, חָתוּל,״ אוֹמֵר דָּנִי.", en: "“Hello, cat,” says Dani." },
    ],
    questions: [
      { q: "Where is Dani going when the story begins?", opts: ["To work", "To the beach", "To the market", "To a café"], correct: 2, ev: "יוֹם אֶחָד, דָּנִי הוֹלֵךְ לַשּׁוּק." },
      { q: "What does Dani suddenly hear?", opts: ["Music", "A small sound", "A telephone", "Rain"], correct: 1, ev: "פִּתְאוֹם הוּא שׁוֹמֵעַ קוֹל קָטָן." },
      { q: "What does the little cat look like, and how does it feel?", opts: ["Black and sleepy", "Small, white, and very hungry", "Big and angry", "Orange and happy"], correct: 1, ev: "לְיַד הַחֲנוּת יוֹשֵׁב חָתוּל קָטָן וְלָבָן. הֶחָתוּל רָעֵב מְאוֹד." },
    ],
  },
  {
    num: "ג׳",
    titleHe: "חָלָב וְדָג קָטָן",
    titleEn: "Milk and a Small Fish",
    sentences: [
      { he: "דָּנִי חוֹזֵר הַבַּיְתָה, וְהֶחָתוּל הוֹלֵךְ אַחֲרָיו.", en: "Dani goes back home, and the cat follows him." },
      { he: "״אַתָּה רוֹצֶה לֶאֱכֹל?״ שׁוֹאֵל דָּנִי.", en: "“Do you want to eat?” asks Dani." },
      { he: "הוּא נוֹתֵן לֶחָתוּל חָלָב וְדָג קָטָן.", en: "He gives the cat milk and a small fish." },
      { he: "הֶחָתוּל אוֹכֵל מַהֵר.", en: "The cat eats quickly." },
      { he: "אַחַר כָּךְ הוּא יָשֵׁן עַל הַסַּפָּה שֶׁל דָּנִי.", en: "Afterwards, he sleeps on Dani's sofa." },
      { he: "״אֵיזֶה חָתוּל עָצֵל!״ צוֹחֵק דָּנִי.", en: "“What a lazy cat!” laughs Dani." },
    ],
    questions: [
      { q: "What happens when Dani goes home?", opts: ["The cat runs away", "The cat follows him", "He forgets about the cat", "He buys the cat"], correct: 1, ev: "דָּנִי חוֹזֵר הַבַּיְתָה, וְהֶחָתוּל הוֹלֵךְ אַחֲרָיו." },
      { q: "What does Dani give the cat?", opts: ["Water and bread", "Milk and a small fish", "Cat food", "Coffee"], correct: 1, ev: "הוּא נוֹתֵן לֶחָתוּל חָלָב וְדָג קָטָן." },
      { q: "What does the cat do after eating?", opts: ["Goes back to the shop", "Plays with Dani", "Sleeps on Dani's sofa", "Says thank you"], correct: 2, ev: "אַחַר כָּךְ הוּא יָשֵׁן עַל הַסַּפָּה שֶׁל דָּנִי." },
    ],
  },
  {
    num: "ד׳",
    titleHe: "שֵׁם לֶחָתוּל",
    titleEn: "A Name for the Cat",
    sentences: [
      { he: "בָּעֶרֶב, הֶחָתוּל עוֹד שָׁם.", en: "In the evening, the cat is still there." },
      { he: "״אַתָּה צָרִיךְ שֵׁם,״ אוֹמֵר דָּנִי.", en: "“You need a name,” says Dani." },
      { he: "הוּא חוֹשֵׁב וְחוֹשֵׁב.", en: "He thinks and thinks." },
      { he: "״אֲנִי יוֹדֵעַ! קוֹרְאִים לְךָ לָבָן, כִּי אַתָּה לָבָן כְּמוֹ חָלָב.״", en: "“I know! Your name is Lavan, because you are white like milk.”" },
      { he: "הֶחָתוּל אוֹמֵר ״מִיָּאוּ״ — אוּלַי זֶה ״כֵּן״ בִּשְׂפַת הַחֲתוּלִים.", en: "The cat says “meow” — maybe that means “yes” in cat language." },
      { he: "עַכְשָׁו לְדָנִי יֵשׁ חָבֵר חָדָשׁ.", en: "Now Dani has a new friend." },
      { he: "וְלֶחָתוּל לָבָן יֵשׁ בַּיִת.", en: "And Lavan the cat has a home." },
    ],
    questions: [
      { q: "What name does Dani give the cat?", opts: ["Danny Junior", "Shuki", "Lavan", "Boker"], correct: 2, ev: "קוֹרְאִים לְךָ לָבָן, כִּי אַתָּה לָבָן כְּמוֹ חָלָב." },
      { q: "Why does Dani choose this name?", opts: ["The cat is lazy", "The cat is white like milk", "It was his grandfather's name", "The cat likes milk"], correct: 1, ev: "כִּי אַתָּה לָבָן כְּמוֹ חָלָב." },
      { q: "How does the story end?", opts: ["The cat goes back to the street", "Dani takes the cat to a vet", "Dani has a new friend, and the cat has a home", "The cat runs to the market"], correct: 2, ev: "עַכְשָׁו לְדָנִי יֵשׁ חָבֵר חָדָשׁ. וְלֶחָתוּל לָבָן יֵשׁ בַּיִת." },
    ],
  },
];

export const GLOSS = {
  "דָּנִי": { g: "Dani (a name)" },
  "גָּר": { g: "lives", n: "root ג-ו-ר · masculine" },
  "בְּתֵל": { g: "in Tel-", n: "בְּ = in" },
  "אָבִיב": { g: "Aviv", n: "אָבִיב also means “spring”" },
  "הוּא": { g: "he" },
  "בְּדִירָה": { g: "in an apartment", n: "דִּירָה = apartment" },
  "קְטַנָּה": { g: "small", n: "feminine of קָטָן" },
  "בִּרְחוֹב": { g: "on … Street", n: "רְחוֹב = street" },
  "דִּיזֶנְגּוֹף": { g: "Dizengoff", n: "a famous Tel Aviv street" },
  "בַּבֹּקֶר": { g: "in the morning", n: "בֹּקֶר = morning" },
  "שׁוֹתֶה": { g: "drinks", n: "root שׁ-ת-ה" },
  "קָפֶה": { g: "coffee" },
  "בַּמִּרְפֶּסֶת": { g: "on the balcony", n: "מִרְפֶּסֶת = balcony" },
  "אוֹהֵב": { g: "loves", n: "root א-ה-ב" },
  "אֶת": { g: "(marks the object)", n: "no English equivalent — it points to a specific object" },
  "הָעִיר": { g: "the city", n: "עִיר = city" },
  "הָרְחוֹב": { g: "the street" },
  "מָלֵא": { g: "full (of)" },
  "אֲנָשִׁים": { g: "people", n: "plural of אִישׁ (person)" },
  "אוֹפַנַּיִם": { g: "bicycles", n: "a “pair” word, like מִשְׁקָפַיִם (glasses)" },
  "וַחֲתוּלִים": { g: "and cats", n: "וְ = and" },
  "יֵשׁ": { g: "there is / there are" },
  "הַרְבֵּה": { g: "many, a lot of" },
  "חֲתוּלִים": { g: "cats", n: "plural of חָתוּל" },
  "רוֹאֶה": { g: "sees", n: "root ר-א-ה" },
  "אוֹתָם": { g: "them", n: "אֶת + הֵם" },
  "כָּל": { g: "every, all" },
  "יוֹם": { g: "day" },
  "אֶחָד": { g: "one", n: "יוֹם אֶחָד = one day" },
  "הוֹלֵךְ": { g: "walks, goes", n: "root ה-ל-ך" },
  "לַשּׁוּק": { g: "to the market", n: "שׁוּק = market" },
  "פִּתְאוֹם": { g: "suddenly" },
  "שׁוֹמֵעַ": { g: "hears", n: "root שׁ-מ-ע" },
  "קוֹל": { g: "a sound, a voice" },
  "קָטָן": { g: "small" },
  "מִיָּאוּ": { g: "meow!" },
  "לְיַד": { g: "next to", n: "יָד = hand" },
  "הַחֲנוּת": { g: "the shop", n: "חֲנוּת = shop, store" },
  "יוֹשֵׁב": { g: "sits", n: "root י-שׁ-ב" },
  "חָתוּל": { g: "a cat" },
  "וְלָבָן": { g: "and white" },
  "הֶחָתוּל": { g: "the cat", n: "הַ becomes הֶ before חָ" },
  "וְהֶחָתוּל": { g: "and the cat" },
  "רָעֵב": { g: "hungry" },
  "מְאוֹד": { g: "very" },
  "מִסְתַּכֵּל": { g: "looks (at)", n: "root ס-כ-ל · goes with עַל" },
  "עַל": { g: "on, at" },
  "שָׁלוֹם": { g: "hello", n: "literally “peace”" },
  "אוֹמֵר": { g: "says", n: "root א-מ-ר" },
  "חוֹזֵר": { g: "returns, goes back", n: "root ח-ז-ר" },
  "הַבַּיְתָה": { g: "home(ward)", n: "the ־ָה ending means “toward”" },
  "אַחֲרָיו": { g: "after him", n: "אַחֲרֵי + הוּא" },
  "אַתָּה": { g: "you (m.)" },
  "רוֹצֶה": { g: "want(s)", n: "root ר-צ-ה" },
  "לֶאֱכֹל": { g: "to eat", n: "infinitive of אוֹכֵל" },
  "שׁוֹאֵל": { g: "asks", n: "root שׁ-א-ל" },
  "נוֹתֵן": { g: "gives", n: "root נ-ת-ן" },
  "לֶחָתוּל": { g: "to the cat", n: "לְ + הֶחָתוּל" },
  "חָלָב": { g: "milk" },
  "וְדָג": { g: "and a fish", n: "דָּג = fish" },
  "אוֹכֵל": { g: "eats", n: "root א-כ-ל" },
  "מַהֵר": { g: "quickly, fast" },
  "אַחַר": { g: "after", n: "אַחַר כָּךְ = afterwards" },
  "כָּךְ": { g: "so, thus", n: "אַחַר כָּךְ = afterwards" },
  "יָשֵׁן": { g: "sleeps" },
  "הַסַּפָּה": { g: "the sofa", n: "סַפָּה = sofa" },
  "שֶׁל": { g: "of, belonging to" },
  "אֵיזֶה": { g: "what a…!", n: "also “which?”" },
  "עָצֵל": { g: "lazy" },
  "צוֹחֵק": { g: "laughs", n: "root צ-ח-ק" },
  "בָּעֶרֶב": { g: "in the evening", n: "עֶרֶב = evening" },
  "עוֹד": { g: "still, more" },
  "שָׁם": { g: "there" },
  "צָרִיךְ": { g: "need(s)" },
  "שֵׁם": { g: "a name" },
  "חוֹשֵׁב": { g: "thinks", n: "root ח-שׁ-ב" },
  "וְחוֹשֵׁב": { g: "and thinks" },
  "אֲנִי": { g: "I" },
  "יוֹדֵעַ": { g: "know(s)", n: "root י-ד-ע" },
  "קוֹרְאִים": { g: "(they) call", n: "קוֹרְאִים לְךָ = you are called" },
  "לְךָ": { g: "to you (m.)" },
  "לָבָן": { g: "white", n: "also the cat's name — Lavan" },
  "כִּי": { g: "because" },
  "כְּמוֹ": { g: "like, as" },
  "אוּלַי": { g: "maybe" },
  "זֶה": { g: "this, that, it" },
  "כֵּן": { g: "yes" },
  "בִּשְׂפַת": { g: "in the language of", n: "שָׂפָה = language" },
  "הַחֲתוּלִים": { g: "the cats" },
  "עַכְשָׁו": { g: "now" },
  "לְדָנִי": { g: "to Dani", n: "לְדָנִי יֵשׁ = Dani has" },
  "חָבֵר": { g: "a friend" },
  "חָדָשׁ": { g: "new" },
  "וְלֶחָתוּל": { g: "and to the cat" },
  "בַּיִת": { g: "a house, a home" },
};
